### ISSUE TITLE
Roles - tentative meeting (if people want to discuss further)

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#11]
@hackseq/steering_committee 
Monday, March 21st, 5:30 pm 
Skype: adrizua

**Comment by sjackman** [comment]
I prefer GitHub issues and in-person meetings myself over Skype. I'm happy with my role!

**Comment by ttimbers** [comment]
Closing this issue, please see [#1](https://github.com/hackseq/October_2016/issues/1) for continued discussions in this area.
