### ISSUE TITLE
Sponsorship tiers

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#12]
@ababaian Thanks for uploading our sponsors and partners! We are having 4 Sponsorship tiers: 
MegaBase ($6000), KiloBase ($4000), BasePair ($2000), Nucleotide (<$2000), which will be reflected in the size of the logos. I will save each logo using the first letter of the corresponding tier so you can organize them.
Most logos have a white background and although some organizations are picky about that, it would good to have them in the website color if we can (look who the nwHacks did it https://2016.nwhacks.io/). Would that be doable? 
Thanks!

**Comment by ababaian** [comment]
I can do this as long as we get good quality png/jpeg or better yet .ai/.svg files from the sponsors.
