### ISSUE TITLE
future of hackseq - May meeting

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#13]
@ttimbers @minisciencegirl Since we will be discussing the possibilities to create a new group (or association/co-op...) during our next meeting, I think it is important to invite Will and others from VanBUG. Are there other groups we should include in the conversation? @ababaian

**Comment by minisciencegirl** [comment]
I am a bit confused about this discussion of creating a new group or association/ co-op for hackseq and potential benefits for doing so. Is this related to discussions that happened in #1 and #11? If so, could we please keep threads on the same topic in the same issue for tracking purposes? If not, is it possible to get a bit more background for this discussion? Thanks.

**Comment by adrisua** [comment]
Is this related to discussions that happened in #1 and #11?
- Yes

Could we please keep threads on the same topic..?
- OK

**Comment by ttimbers** [comment]
Closing this issue, please see [#1](https://github.com/hackseq/October_2016/issues/1) for continued discussions in this area.
