### ISSUE TITLE
Team leaders form

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#15]
@sjackman @cloucks @Brittdrog 
This issue has a new home 
https://github.com/ttimbers/October_2016_private/issues/4
Draft for the team leader application:
https://docs.google.com/forms/d/10n52V3flb7Z9z-ulBqAHS8tWVG2ov4b13BQLWYs4tRc/edit?usp=sharing
@DCGenomics please feel free to give us your feedback 
cc: @ababaian @ttimbers @brunogrande @GalenWright @minisciencegirl @santina

**Comment by cloucks** [comment]
Thanks @Brittdrog and @sjackman for your improvements!

**Comment by GalenWright** [comment]
Hey, I think the team leader application form looks great! Just a couple of suggestions, feel free to use them or not:
- In one of the example forms, there was a field for approximate geographic location. I think this would be useful, as well as one for the applicant's related institute
- Section 1, where it asks are you available for the three days - should we give a rough approximate hours expected?
- Likewise with regards to times with the mentorship availability.
- Perhaps we should give a brief description of what being a mentor would entail.

**Comment by cloucks** [comment]
@GalenWright thanks for your great suggestions! @adrisua have the specific start and end times been decided for the three days?

**Comment by DCGenomics** [comment]
We usually run from 9-6 with some networking time after.

This also seems to decrease burnout (instead of working 24 hours).  Many
folks will continue making commits after networking time.

**Comment by sjackman** [comment]
I'd like to find out what software they need for their analysis, make sure that there are Homebrew-science formula for that software, and possibly create a machine image with it preinstalled. That is, one machine image shared by all teams with all the software installed on it. There will likely be some overlap between groups. I don't think this question needs to go on the original application. We can ask the team leaders later what software they need.

**Comment by cloucks** [comment]
I wrote little blurbs for the team leader and mentor descriptions in the team leader application (partly drawn from the emails we will send out to potential team leaders). Please feel free to edit/improve them.

**Comment by cloucks** [comment]
@ttimbers I also made a separate mentorship application form: https://docs.google.com/forms/d/1Mps9NRYI70d5b0kznMqbUINGSETwqNJz6ImyVPfy8xc/edit?usp=sharing

**Comment by ttimbers** [comment]
@cloucks thanks for making this. Can we add a couple more questions to assess mentors knowledge level and ask them to write a couple sentences on why they want to participate? Raising the bar a little will hopefully help ensure those who sign-up to become mentors, actually show up to the event.

**Comment by cloucks** [comment]
Good idea @ttimbers

**Comment by DCGenomics** [comment]
Great point!  Matt and I have a bunch of amis from previous teams that
might be helpful.  I believe we have a "base ami" too

**Comment by adrisua** [comment]
@cloucks  Yes, dates are set.
The forms look great!!

**Comment by nyetsche** [comment]
@sjackman I have an AMI and a "manifest" of the software installed for the last hackathons. It's in a Google doc, I'll share it with you.

It's always hard to pin down just what is needed (and versions) so it's more of a best guess than perfect AMI. It's all manual `./configure && make` installed into `/opt`, and then I added that to `$PATH` in `/etc/profile.d/` just to make it easy for the users.

**Comment by nyetsche** [comment]
Actually, as an addendum, I had a lot of help/convenience for that AMI by using BioBuilds - https://biobuilds.org/downloads/ - a twice-yearly, curated, pre-compiled collection of common bioinformatics tools.

I'll also take a look at `homebrew-science` and a homebrew install for Linux next time.

**Comment by sjackman** [comment]
When are the team leader project proposals due?

**Comment by ttimbers** [comment]
From discussions [here](https://github.com/hackseq/October_2016/issues/18) @sjackman suggested we align team leader project proposals to be due on June 2nd to align with ASHG. I agree, what do others think?

@sjackman if we don't come to a consensus on the date before VanBUG today, let's just announce the April 30th date, and we can always "extend" it later if that is what we decide to do. Sound good?

**Comment by sjackman** [comment]
If we can quickly decide on June 2nd, I'd like to announce that date.
@hackseq/steering_committee What do you all say?

**Comment by sjackman** [comment]
Once we have decided, @ababaian can you update the web page with the project proposal due date? Perhaps even on the front page.

**Comment by ababaian** [comment]
If I remember, originally we wanted the _participant_ applications to be due ~ June 2nd so they could book their plane tickets accordingly. That might not work if we added an additional team leader's choosing their teams to the process.

Unless we do something like
- April 30th Team Leader Due.
- May 15 Participant Due.
- June 1st Decide on teams.
  
  Not sure if that's feasible tbh. Using a June 2nd Team Leader date might be better.

**Comment by Brittdrog** [comment]
I agree with @ababaian that we need to co-ordinate our application deadlines so that people can book their flights accordingly. I think we should probably keep April 30th for team leader applications and make participant deadlines June 2nd (coinciding with ASHG abstract deadlines). May 15th may be a bit of a tight deadline to advertise projects and get participant applications in.

We could always re-evaluate these deadlines if we do not have enough applicants?

**Comment by sjackman** [comment]
April 30th is only two weeks away. Does that give enough time for people to hear about it by word of mouth and submit an application?

**Comment by GalenWright** [comment]
We could extend Britt's dates by two weeks, which would give the team leaders a month to put together applications and allow more time for word to spread about the event. It would also give us the opportunity to email the invited team leaders again, reminding them of hackseq in case they forgot about the previous email.

**Comment by sjackman** [comment]
The motivation for the June 2nd decide-on-teams deadline was to get the info to the leaders and participants in time for them to schedule their travel. ASHG abstracts are due June 2nd, but they won't hear back regarding acceptance until mid-August, and probably won't schedule their travel until they've heard back. How about this schedule?

Thu June 2: Team leader project proposal due
Thu Jun 30: Participant application due
Fri Jul 15: Decide on teams

https://www.ashg.org/2016meeting/pages/abstract_faq.shtml

> Q. When will I be notified of acceptance?
> A. The information will be available on the ASHG website in mid-August.

**Comment by GalenWright** [comment]
The hackseq account just received an email about the deadline for team leader applications. I looked on our website and could not find a date mentioned under http://www.hackseq.com/participate/. 
@ababaian could you possibly include the team leader deadline, with the revised date, on this page? Thanks!

**Comment by ababaian** [comment]
Done and added due date to the top of the application form.

**Comment by Brittdrog** [comment]
@cloucks - do you think we should add the travel award application info to the team leader application forms? We could maybe send emails to the applicants who have already applied to inform them that they can apply for travel awards?

**Comment by cloucks** [comment]
@Brittdrog I think it's a good idea to add the travel award info to the team leader application, and if only trainees are eligible we don't have to worry about the people who already applied.

**Comment by Brittdrog** [comment]
@cloucks - Perfect!

**Comment by adrisua** [comment]
@Brittdrog @cloucks Just wondering where the team leader applications live. How many do we have so far? @minisciencegirl are the twitter feeds being effective or should we look for alternative channels?

**Comment by cloucks** [comment]
@adrisua @Brittdrog @minisciencegirl We're at 7 applications now (a new one came in today). You can access the team leader application form here (the hackseq email account has access): https://docs.google.com/forms/u/0/d/10n52V3flb7Z9z-ulBqAHS8tWVG2ov4b13BQLWYs4tRc/edit#response=ACYDBNgWYKcK99nIqN1pD6vcVrcVKaB6IGyMFn-kf83x4wlhRPv_0bxhRxoLzCw

**Comment by minisciencegirl** [comment]
@adrisua: I just looked up our Twitter Analytics and the data look better than I expected. We have 6.5K impressions for the last month, with about 238 impressions per day. This is not bad considering that we have only about 70 followers. A big thank you @adrisua for getting the ASHG account to retweet our tweets and follow us - that definitely drove traffic to our account.

For anyone interested in tracking our twitter impressions: https://analytics.twitter.com/user/hackseq/tweets

With that said, I don't think our Twitter feed should be the prime source of advertising.  In part because it does take time to build up followers. For team leader application, it was helpful to directly contact people (i.e. Galaxy, Deanna Church etc). Any other ideas for advertising the participant applications?

**Comment by adrisua** [comment]
Let's extend the deadline to June 16th? @hackseq/steering_committee Early next week we could start sharing the info in our own departments, Faculties... @cloucks @Brittdrog Do you have a template we could use for departmental newsletters, mailing lists? I could reach out to the Faculty of Science and Forestry at UBC

**Comment by sjackman** [comment]
A two-week extension seems reasonable.

**Comment by Brittdrog** [comment]
I just checked the applications and we have 10 applications in. Maybe some of the hackseq members can put in an application too (I see @sjackman has already put in an application).

My worry is that people are already concerned about booking [accommodation](https://twitter.com/girlscientist/status/738409594955911168) and we still need to get participants to apply. We are also getting contacted by team leaders to find out when they will find out whether their applications have been accepted.

Here is the previous [template](https://github.com/hackseq/October_2016_private/blob/master/TeamLeaders/Email_for_distribution_to_societies.pdf) for sending out to departments if we still decide to extend the deadline (the deadline date will just need to be changed).

**Comment by sjackman** [comment]
Shall we send out e-mails with abstracts to participants on Thursday June 9? We can in the next few days solicit more project proposals directly from people we know.

**Comment by Brittdrog** [comment]
Sounds good to me.

**Comment by cloucks** [comment]
I like that idea too.

**Comment by adrisua** [comment]
New deadline for team leaders applications: June 8th. @ababaian @brunogrande @santina @ttimbers Would you mind sharing this in your network @Brittdrog thanks for the template: October_2016_private/TeamLeaders/Email_for_distribution_to_societies.pdf

**Comment by GalenWright** [comment]
@adrisua I may have misinterpreted it, but weren't we going to keep the team leader applications officially closed, but try and convince a couple of people to apply? Personally, I don't think we should announce an extended deadline again as it makes it look like we are struggling to get applications

**Comment by GalenWright** [comment]
Sorry, @ababaian didn't mean to tag you directly - it was meant for @adrisua

**Comment by minisciencegirl** [comment]
I agree with @GalenWright. I thought we were aiming for 10 applications to begin with?

**Comment by sjackman** [comment]
10–20 as I recall.

**Comment by cloucks** [comment]
I want to mention that we have 10 applications but only 9 submitted abstracts. There is one person who is unable to commit for the entire thing.

**Comment by adrisua** [comment]
I think it is fair to give equal opportunity to everyone that would like to apply - since we are allowing late applications. Also, it will give our participants more options and diversity (if more people apply).

**Comment by adrisua** [comment]
I shared the info with my departments (since I hadn't done it and people were asking me about it). Sorry for the confusion. If June 8th is still too late let me know.

**Comment by GalenWright** [comment]
No worries, I guess we can phrase it on twitter, "Due to popular demand, we've decided to extend our team leader applications..."

**Comment by ttimbers** [comment]
I'm not sure I agree with extending the deadline. 9 teams x 6 people per
team is 54 people. Plus all of us, and any mentors that wasn't too pop by
and help out. That's a big event!

**Comment by ttimbers** [comment]
I'm not sure I agree with extending the deadline. 9 teams x 6 people per
team is 54 people. Plus all of us, and any mentors that wasn't too pop by
and help out. That's a big event!
On Jun 3, 2016 12:43 PM, "Galen Wright" <notifications@github.com> wrote:

No worries, I guess we can phrase it on twitter, "Due to popular demand,
we've decided to extend our team leader applications..."

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hackseq/October_2016/issues/15#issuecomment-223675659>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGjAeFxk9Ni3YI2MwZLhFKOjiQblj2Xrks5qIIP5gaJpZM4H2yiw>
.
