### ISSUE TITLE
New logo and link

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#16]
@ababaian Would you mind adding the ASHG logo in the Partners Section and linking it to: http://www.ashg.org/2016meeting/? Also in the front page below the dates, would you mind adding: "A satellite event of the ASHG meeting". Thanks!

**Comment by adrisua** [comment]
Also the NCBI one please (in the Partners Section). Thanks!

**Comment by ababaian** [comment]
Done and done. It's not super pretty right now but I'll have some time soon to hack together the CSS code to make the whole thing look really pretty.
