### ISSUE TITLE
Standard date format

### ISSUE THREAD

**Issue by sjackman** [hackseq/October_2016#17]
@hackseq/steering_committee 

Can we please use the standard ISO 8601 YYYY-MM-DD date format in our GitHub issues, communications and spreadsheets? Pretty please?

![](https://imgs.xkcd.com/comics/iso_8601.png)
https://xkcd.com/1179/

**Comment by sjackman** [comment]
With no objections, I herby declare declare this motion passed unanimously.

**Comment by BrunoGrandePhD** [comment]
You have my full and unfaltering support for ISO 8601.

**Comment by santina** [comment]
Me too! 

Signed: 
Santina Lin
April 12th, 2016, tue
