### ISSUE TITLE
Child care

### ISSUE THREAD

**Issue by sjackman** [hackseq/October_2016#20]
Would we like to consider offering child care if there's interest?

**Comment by ttimbers** [comment]
Yes - a discussion on this has already been started [here](https://github.com/ttimbers/October_2016_private/issues/5), so I will close this issue and we can keep the discussion in one place.

**Comment by sjackman** [comment]
Ah, sorry. I missed that. Thanks, Tiffany.
Duplicate of https://github.com/ttimbers/October_2016_private/issues/5

**Comment by DCGenomics** [comment]
404 for me

**Comment by sjackman** [comment]
That thread is private. Here's what I've written:

We could talk to UBC child care. The weekend during the day is probably quiet for them.

Nannies on Call charges
$32 per booking plus
$16 per hour for the first eight hours plus
$24 per hour for each additional hour after the first eight plus
$3 per hour per child after the first child
See https://www.nanniesoncall.com/families/on-call/vancouver/
We would need a location for the children.

So rough estimate for four children for ten hours per day:
32 + 16 \* 8 + 24 \* 2 + 3 \* 10 \* 3 = $298 per day
This estimate gives a starting point, but we could probably hire a private nanny for cheaper. $30 per hour seems high.

[UBC Child Care, occasional care](http://www.childcare.ubc.ca/osprey/)

> Osprey Occasional Care
> Scheduled to open in 2016, Osprey Occasional Care will provide child-minding for children between the ages of eighteen months and six years. With this program, we intend to provide families who do not require regular on-going child care with a safe and welcoming occasional child care option.

$20 per child per hour, so maybe Nannies on Call is cheaper. It would still be worth asking them.
See http://www.childcare.ubc.ca/fee-schedule/
