### ISSUE TITLE
Example projects

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#22]
Hi @DCGenomics, 
Do you have a list of project titles and maybe the description of them from previous hackathons you were involved in? We would like to see what a successful project look like and provide some examples to our potential team leaders. Thanks!

**Comment by DCGenomics** [comment]
Sure!  I can send 'em over on Sunday.

Also, many one line descriptions can be seen on github.com/NCBI-hackathons

Cheers!

Ben

On Fri, Apr 22, 2016 at 2:25 PM, Santina Lin notifications@github.com
wrote:

> Hi @DCGenomics https://github.com/DCGenomics,
> Do you have a list of project titles and maybe the description of them
> from previous hackathons you were involved in? We would like to see what a
> successful project look like and provide some examples to our potential
> team leaders. Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hackseq/October_2016/issues/22

## 

What have you done today to make the world a better place?

**Comment by santina** [comment]
@DCGenomics Thank you! Really appreciate the prompt response :)

**Comment by DCGenomics** [comment]
Here are some initial project titles.

Some of them evolved into the ones you see on the NCBI-hackathons github
repos.

Prediction of immunogenicity from cancer and bacterial peptides
Deriving Structural Variants from RNA-seq Data Using GATK
Building a pipeline for determining RNA sequence variability in neurons
from any species
Small molecule docking in solved protein structure space.  Effects of
network bifurcation.
Integration of ClinVar/dbGaP data into protein structure interfaces
Genome Wide View of RNA-seq data
Statistical Network Analysis of Variants
Automated Epitope Analysis from TCR clones
 Verification of Structural Variant Data with Information from Public
Datasets
Building a pipeline network analysis and display of SNPs
SRA2R -- building a BioConductor module to import data from SRA
Looking at RNAseq network pertubations in specific carcinomas
Deriving Quaternary Interactions of Clinically Relevant Mutations from
Protein Structure
Creating an interface for metadata sorting*
Finding all quaternary structural associations of ClinVar variants
Homogenous mapping of 50,101 RNAseq runs to the human genome
Building a pipeline for automated upload and comparison of RNAseq
expression data; establishing a standard format for this process
Enabling easy and rapid RNAseq analysis from public datasets: Building a
GUI for the Sequence Read Archive*
Metadata Normalization for RNAseq Analysis.
Automatic Scanning of NGS Datasets for Disease Relevant Variants
A Pushbutton Tool for .vcf Filtering
Molecular Matching in Myeloma: Combining RNAseq Data with Drug Response
Profiles**
Automated Genome Selection from Complex Phenotypic Data in dbGaP
Using SEQR (PSSM BLAST) to Check for Gross (Domain Level) Differences in
RNAseq Datasets
Push Button Genomics Analysis with BLAST*
Building an Educational Environment to Teach Genomic Mapping and Ultrafast
BLAST; .sam Format Comparison
Building an Indexing, Distribution and Updating System for Bioinformatics
Virtual Machines*

###

Cheers!

Ben

On Fri, Apr 22, 2016 at 10:23 PM, Santina Lin notifications@github.com
wrote:

> @DCGenomics https://github.com/DCGenomics Thank you! Really appreciate
> the prompt response :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hackseq/October_2016/issues/22#issuecomment-213652008

## 

What have you done today to make the world a better place?
