### ISSUE TITLE
Workshops/talks during hackathons to increase the exposure 

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#23]
Hi team, 

Taken from the [Hackathon Guide book](https://hackathon.guide/), we might want to consider having a parallel track with training workshops or talks to make our event even more attractive to participants. 

I know for some people, the word "hackathon" has a bad rap because of some unhealthy practices (allnigters, caffeine, alcohol) in some hackathons and a negative connotation with too much competition or unfriendly to those new to programming. If you've seen the twitter thread on the picture posted by @ttimbers and the responses on that thread, you'll understand. If not, just read the hackathon guidebook, it's great. 

If we could include interesting workshops and talks, we can get more people to come to the event for the sake of learning. We then have a chance to show them that hackathons aren't that unapproachable, and this will benefit us greatly when we organize HackSeq next year. And who knows, maybe those who initially only want to attend the workshops would become interested in working on the projects during that weekend. 

This could help us set ourselves apart from other hackathons that only have the "hacking" part as a single track. Working for 3 days straight can be quite boring, so if we have programs running on the side that people can attend from time to time, they'll definitely think of the whole experience as a much more fruitful one than sitting in front of a computer all weekend. 

Pro's: 
- Getting more traffic from those who want to learn, get more participants 
- Possibly getting more sponsorship if you give sponsors a chance to talk. For example, I'd love to hear what 10XGenomics have to offer. You can then give people a chance to network as well. 
- You can take break from coding and listen to fun talks! 
- Giving people a chance to give a talk

Con: 
- More work for us to have to find speakers and rooms for this, as well as more complicated schedule. However, we don't even need to already finalize the schedule for the talk before the end of the sign-up date (June 30). We can constantly update it until the day of the event.

**Comment by santina** [comment]
Just to update the status on this since our meeting yesterday: So I will add a speaker option to the applicant form to see how much interest there are.  This information should also be available on the website.

**Comment by BrunoGrandePhD** [comment]
I'm going to go through the original participant form and contact anyone who offered to lead a workshop.
