### ISSUE TITLE
Should we move away from the term "hackathon"?

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/October_2016#24]
I think we can all agree that we should aim for diversity among our team leaders and participants. When I was reading [the private thread](https://github.com/hackseq/October_2016_private/issues/5) on encouraging women to participate, [this one tweet](https://twitter.com/erinrwhite/status/707956467224190976) came to mind. The gist of it is that the name we give the event might have a strong influence on who it attracts. In their admittedly small experience, the term "hackathon" mostly attracted male computer scientists. 

I speculate that this has to do with the connotation that "hackathon" carries. @santina alluded to this in Issue #23. Briefly, it usually evokes a very competitive environment meant for computer nerds that often involves all-nighters, pizza and beer. @ttimbers [brought up](https://twitter.com/TiffanyTimbers/status/723584334867755008) this potential issue on Twitter and some people corroborated the negative connotation associated with the word "hackathon" (see [1](https://twitter.com/StefanieButland/status/723588955665367040) and [2](https://twitter.com/terrimyu/status/723665202953248768)). 

Obviously, this doesn't describe what we're trying to organize. We want to be inclusive and fun, not exclusionary and stressful. We want people to explore new ideas without the pressure of having to deliver on it. We want to encourage creativity, not stifle it. So, I'm afraid we might be shooting ourselves in the foot by describing ourselves as a Genomics Hackathon and giving off an image that doesn't represent what we aim to be. 

Now, if we were to move away from calling ourselves a Genomics Hackathon, then what do we call ourselves? @ttimbers [suggested](https://twitter.com/TiffanyTimbers/status/723584334867755008) **Unconference**. My only fear with this term is that people are unfamiliar with what it means, which might be a good thing and incite curiosity. A synonym for hackathon which might not have as much negative connotation is a **Code Festival**, which drops the marathon reference and makes it sound more fun, but that's open to debate. It also might still preferentially attract more technical people. 

Another awkward issue is the name Hackseq. We've kinda already went all in with that name. I don't know if it's worth dropping the Hackseq name. Maybe using it with a friendlier description might be enough to attract more people, _e.g._ Hackseq Unconference or Hackseq Code Festival. I'm curious to hear your thoughts on the matter. If the consensus is to drop the hackathon descriptor, then we can perhaps do a vote. Other name suggestions are welcome!

**Comment by DCGenomics** [comment]
FWIW, I discussed that particular tweet with some female Hackathon
participants and they found it ridiculous.

**Comment by DCGenomics** [comment]
That said, the biggest predictor we have seen of having diversity in
participants is having diversity in team leads.  With that in mind, and in
general, I would suggest approaching those who you think would be strong
team leads and asking them to participate.

**Comment by ttimbers** [comment]
Another word that I've seen organizations use is "sprint", for example the Mozilla Science Global Sprint that has been happening for the last 3 years. Since we've already got hackseq on all our documents & accounts, it might be easier to keep it + add a descriptor. Such as those @brunogrande already suggested and a couple others:

Hackseq Unconference
Hackseq Codefest
Hackseq Sprint
Hackseq Code Sprint

If anytime has any other name suggestions, please throw them in the thread and I'll make a survey so we can vote. I'll also include the option to keep the name as it currently is in the survey.

**Comment by Brittdrog** [comment]
This is an interesting discussion - I am in two minds.

In terms of logistics, we have already contacted several people and have set up websites, accounts, etc using our name and describing the event as a genomics hackathon. I think it looks a little unprofessional to change this now (esp given that our original leader application deadline was 30 April).

We are also basing our format on previous NCBI hackathons and will be directing applicants to past NCBI hackathon resources for inspiration - it may be confusing if we are no longer labeled as a genomics hackathon.

Personally (as a female), I enjoy beer and pizza;-) and I love the idea of a genomics hackathon - I think we should focus more on encouraging the participation of women e.g. by contacting them personally and by including a statement on our website homepage (e.g.we specifically encourage the participation of trainees, early career investigators, women and minorities). A similar statement was sent out to potential team leaders.

Our women:men ratio is not bad at the moment - 2:1 for people who have indicated that they are interested in being team leaders, 7:4 for our steering committee.

**Comment by ababaian** [comment]
I'm more inclined to keep it as a Genomics Hackathon. The twitter post was comparing "Creative Coding Hackathon" vs. "Creative Coding Workshop" vs. "Creative Coding Lunch Group". Hackathon attracted the most males but also the most computer science students. I think those are not independent variables and in biology the the gender ratio is closer to parity then in compsci. I don't think it's going to be such a dramatic gender skew.

Edit: Also in terms of the 'competitive' nature. I'm skeptical that something with friendly competition would be exclusive. It's not unlike any recreational sports league like beach volleyball for instance. We're all there to have fun but there is a 'toy' extrinsic motivator to focus teams. More important will be the "tone"  which we as organizers set and I think everyone is on the same page that its going to be pretty chill. That's my experience from the previous hackathon I did anyways.

**Comment by ttimbers** [comment]
OK, since most people on this thread have said that they want to keep the term hackathon, and particularly because we have already starting advertising as this, I won't put forward a vote to change the name. I will instead add it to [this list](https://github.com/hackseq/October_2016/blob/master/suggestions_for_next_time.md) of things we might want to reconsider if we plan another such an event in the future.

**Comment by santina** [comment]
In the meeting we said we'll consider this next year since it's too late to change it now.
