### ISSUE TITLE
Put in place a Code of Conduct

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/October_2016#25]
We should put in place a code of conduct for our event. If you're wondering why, you should read [this blog post](http://www.ashedryden.com/blog/codes-of-conduct-101-faq#coc101why) by Ashe Dryden. That blog post links to a few Code of Conducts that we can use. Someone also posted [another one](http://hackcodeofconduct.org/) in the Etherpad for our meeting on 2016-04-22. This isn't urgent, but I wanted to bring it up while I'm thinking about it.

**Comment by ttimbers** [comment]
+1 to adding a code of conduct @brunogrande! We could borrow [this one](http://software-carpentry.org/conduct/) from Software Carpentry or [this one](https://www.mozillascience.org/code-of-conduct) from the Mozilla Science lab.

**Comment by adrisua** [comment]
@brunogrande @ttimbers Which one do you think we could use? Could we just add the link to our website or do we want to work more on it? @ababaian

**Comment by ababaian** [comment]
I'll start compiling a 'participant resources' let me know which thing you guys want.

**Comment by ttimbers** [comment]
I'm good with either code of conduct, but maybe let's go with the Mozilla Science one? I think the Software Carpentry one was written with the focus of a workshop setting, while I think the Mozilla one might be more general about collaborative work and coding?

**Comment by ttimbers** [comment]
Actually, under closer inspection they're both very similar, so either would work. I have no preference.

**Comment by BrunoGrandePhD** [comment]
Indeed, the SWC and Mozilla CoCs are very similar. If you need a tie-breaker, I would go with SWC's CoC because it attributes where it obtained the text (at the bottom).

**Comment by BrunoGrandePhD** [comment]
@ttimbers @adrisua: Are we going with the Software Carpentry code of conduct? I want to include a question in the confirmation of attendance form (see hackseq/October_2016_private#23) that makes participants acknowledge the code of conduct. 

@ababaian: If there is no debate this morning, could you add the code of conduct to the website this afternoon? Thanks!

**Comment by BrunoGrandePhD** [comment]
@ababaian: Preferably, include the entire text on our website, including the attributions at the bottom and cite where it came from. This way, it looks more official. It also allows us to update the email in the text to our hackseq Gmail account.

**Comment by ababaian** [comment]
if it's all the same I think the Mozilla one is more clear. I've started the participants page at www.hackseq.com/participant-resources and code of conduct is online at www.hackseq.com/conduct
