### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#26]
@ababaian The website looks great! I like the new format for the icons of sponsors and partners. Would it be possible to organize the sponsors in the following sections: Gigabase: ECOSCOPE; Megabase: ASHG (this one could be removed from the community partners section)?

**Comment by ababaian** [comment]
Can we request a vector/high quality Ecoscope logo? The one I snagged from the website isn't really good quality.

**Comment by adrisua** [comment]
Would this one work?:
October_2016/website/sponsors/ECOSCOPE.jpg

**Comment by ababaian** [comment]
That one is great. I put bioinformatics under megabase. Let me know if that all looks right.

**Comment by adrisua** [comment]
Thanks! bioinformatics was BasePair. Would you mind to update that?
