### ISSUE TITLE
Reminder - hackseq meeting on 2016-05-17 at Stateside Craft on Commercial Drive

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#27]
@hackseq/steering_committee this is a reminder that we are scheduled to have our next in person meeting this upcoming week, on 2016-05-17 at [Stateside Craft](http://www.statesidecraft.com/) on Commercial Drive. See [the map](https://www.google.ca/maps/place/Stateside+Craft/@49.2703918,-123.0699025,15z/data=!4m2!3m1!1s0x0:0x4ad02d60be118d5d?sa=X&ved=0ahUKEwjl2ZzbwdzMAhUI0GMKHXrpCA8Q_BIIdjAL) for location.

Hopefully this place is a bit quieter than St. Augustines was. I have a reservation for us under Tiffany, and  I checked that no events are going on at the time we are there. At this meeting we can discuss the location/frequency/etc of future meetings. 

The agenda for this meeting has been drafted on this etherpad: http://pad.software-carpentry.org/hackseq. After the meeting, the agenda and the notes will be archived here: https://github.com/hackseq/October_2016/blob/master/meeting_notes/2016-05-17.md.

See you all there!

**Comment by DCGenomics** [comment]
Here's some draft language for #3, bullet point #2.

Congratulations!  You have been selected for the Network Analysis of SNPs
team

###

At the January, 2016 NCBI Hackathon!

Please let us know **_by responding to this string**_ by _5 pm, Monday
December 7th_ if you will be able to attend the [entire] event in Bethesda,
MD.

Thanks for your interest and congratulations!

Much more correspondence to follow if you accept.

###

**Comment by ababaian** [comment]
I won't be able to make it tomorrow. We have family visiting from Germany and are ending up going out of town.

I'll check the minute and do all website stuff starting Thursday

**Comment by BrunoGrandePhD** [comment]
If ever Stateside Craft is too noisy, can we have a backup plan of where we can move to? Perhaps to a nearby coffee shop. I'd rather move to a better place as soon as we realize it's not ideal for a meeting.

**Comment by ttimbers** [comment]
Not sure if the 10 or so of us can fit in a coffee shop, which is why I opted for a pub... But there are several coffee shops across the street within a block or two we could try if its too noisy... Its on the agenda to discuss future meetings. It's hard with people being in different locales, maybe remote is the answer (although I'd be sad not to see you all once in a while!)

**Comment by sjackman** [comment]
It would be difficult to arrange a plan B on short notice. Let's stick with Stateside this time around.
