### ISSUE TITLE
Remote participation at 2016-05-17 meeting

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#28]
@adrisua you noted on the agenda that Ben would be joining us? I am guessing that is remotely? Please let him know that we will be meeting at a pub, and as a large group so he may have trouble hearing things, but he is welcome to watch our planning etherpad (http://pad.software-carpentry.org/hackseq) and comment on it.

**Comment by DCGenomics** [comment]
You guys seem awesome!  I'll likely be at a pub in Toronto for the meeting,
and I'll follow it on the etherpad.

Cheers!

Ben
