### ISSUE TITLE
Docker Bioinformatics image

### ISSUE THREAD

**Issue by sjackman** [hackseq/October_2016#29]
There's a project at the BCGSC to build a Docker image containing all the bioinformatics software in Homebrew/science named ORCA, and I think it could be useful for HackSeq. There's a demo server at the GSC running this image, and we can make use of it for low-to-medium-resource jobs for HackSeq. If you would like an account on this machine to test it out, send me a private message (e-mail or Twitter @sjackman).

**Comment by sjackman** [comment]
Here's the ORCA web page: http://www.bcgsc.ca/services/orca/
ORCA: genOmics Research Container Architecture
ORCA is a platform for bioinformatics analysis. It is suited for those wishing to conduct self-serve analysis using their own existing data.

**Comment by BrunoGrandePhD** [comment]
Could the Mosh mobile shell be added to the list of software included with the Docker image? It would be a nice safeguard in case of crappy Wi-Fi in LSI.

**Comment by sjackman** [comment]
`brew install mobile-shell`
Does it work on ORCA? I didn't test it. I'd like to know.

**Comment by BrunoGrandePhD** [comment]
I didn't end up using mosh. Just ssh.
