### ISSUE TITLE
Web site fixes

### ISSUE THREAD

**Issue by sjackman** [hackseq/October_2016#3]
Hi, Artem. I few minor web site fixes for you. Thanks for the excellent work on the web site!

http://www.hackseq.com/
`The requested social account cannot be found.`

http://www.hackseq.com/apply
`(May 14,15th)` should be `Oct 15-17`

http://www.hackseq.com/contact
`@hack_seq` should be `@hackseq`

**Comment by ababaian** [comment]
Fixed date and twitter account. Note sure what you mean with

> The requested social account cannot be found

**Comment by sjackman** [comment]
The text `The requested social account cannot be found.` used to appear on http://www.hackseq.com/, but is gone now. So it's fixed! Thanks, Artem.
