### ISSUE TITLE
hackseq remote meeting tomorrow (June 7th!)

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#31]
@hackseq/steering_committee this is a reminder that we are having a remote meeting tomorrow on Google hangouts. Here's the deets:

Date: 2016-06-07
Time: 9:00 - 10:00 am PST
etherpad agenda: http://pad.software-carpentry.org/hackseq
Google Hangout link: https://hangouts.google.com/call/fychc5zmkjd6rlbjvfaa37kqyme

**Comment by adrisua** [comment]
I'll be at work so won't be able to join but added a comment about the travel grants.

**Comment by GalenWright** [comment]
Unfortunately I have a last minute Skype interview scheduled at that time tomorrow
