### ISSUE TITLE
Accommodation

### ISSUE THREAD

**Issue by Brittdrog** [hackseq/October_2016#35]
We are having some questions relating to how close the hackseq and ASHG Meeting venues are to each other (for accommodation purposes). So I have made a [map](https://www.google.com/maps/d/edit?mid=1sZaegrYoiuYdD3Ls1Plk7QADPoA) showing where the venues are in relation to one another (with links to accommodation options). Please let me know if anyone else has any good suggestions for accommodation.

**Comment by adrisua** [comment]
what about airbnb?

**Comment by adrisua** [comment]
@Brittdrog I found just what we needed:  http://suitesatubc.com/

**Comment by Brittdrog** [comment]
@adrisua this is the link that I have been sending to anyone who asks:-) It is also in the map indicating the location of hackseq and ASHG

**Comment by adrisua** [comment]
Once we have the final list of participants, we could we ask them if they would like to share a room with others.

**Comment by adrisua** [comment]
@Brittdrog Great! That link has a wide range of options. This is another pricey alternative http://triumfhouse.ca/non-triumf-lab-ubc-rates.php

**Comment by Brittdrog** [comment]
@adrisua - thanks - I have added this link to the map
