### ISSUE TITLE
2016-06-23 hackseq planning meeting tonight

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#38]
@hackseq/steering_committee this is a reminder that there is a hackseq planning meeting tonight at 6:00pm at the Genome Sciences Centre (570 W 7th Ave, 1st floor board room). Call Shaun at 778-235-0342 to be let in.

A meeting agenda has been drafted and exists here: http://pad.software-carpentry.org/hackseq. Please feel free to add anything you would like to discuss that is not currently on the agenda.

Lastly, I apologize, but I am not feeling well and thus cannot attend the meeting. Could someone else please kindly act as secretary in my stead for this meeting?

**Comment by cloucks** [comment]
Hi everyone, I apologize, but I also won't be able to attend the meeting tonight.
