### ISSUE TITLE
Project withdrawal

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#39]
@Brittdrog @cloucks @santina Justin had a family emergency and won't be able to participate :(

**Comment by santina** [comment]
Is it [this project](https://github.com/hackseq/hackseq_projects_2016/issues/8), "Explore high quality RNA-seq data from 2 genotypes of spruce following weevil attack, artificial wounding and untreated controls "  ?  Does that mean I should remove it from the application form?

**Comment by Brittdrog** [comment]
@adrisua - sorry to hear! Thanks for following up on that. 
@santina - that is the correct project. I have removed this project from the website and closed the GitHub issue. Can you please remove it from the application?

**Comment by santina** [comment]
I'll put a note next to it, saying that this project has been closed. Because if I changed the answer fields right now, it might messed up the response form format.
