### ISSUE TITLE
Website offline for now?

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#4]
@ababaian you have been done an amazing job! 
Could we take the website offline for now? We could start adding partners and add more information.

**Comment by ababaian** [comment]
Website is now reduced to cover splash art.

What would you like added before the website is 'online'?

**Comment by adrisua** [comment]
Thanks! I added some comments to the October_2016/website/todo file. 
Let me know what you think.

**Comment by ababaian** [comment]
I've implemented most of the changes and brought sections back online as I've reformatted them.

For now I have a site-wide password that's needed to see the site. It's 'fruitfly'

Take a look and let me know what you think of the things that are online

**Comment by adrisua** [comment]
Should we replace the word ‘genomics’ with ‘omics’? – to include proteomics, metabolomics, etc. 
Could we re-arrange the home page?
Something like:

"CATALYZING BIO+INFORMATICS
We want to mix a diverse set of scientists for three days to catalyze open & innovative solutions to today's biggest 'omics' problems"

Followed by: 

"PARTICIPATE
A hackathon is a great place to meet like-minded individuals, learn, and collaborate to create something big”
“Sounds cool? Join *us?:”

Have two sections side by side:
On the left 

“COLLABORATORS:
Hackseq is open to everyone with coding experience. The focus is on empowering students and trainees who want to use their skills and knowledge in a creative new way
-   Apply to the projects you're excited about
-   Bring your skills to the team
-   Collaborate!”

On the right: 

“TEAM LEADERS
Have an idea for a project?
That's great! Apply and tell us about the project and a rough team composition you think the project will need.
If you require child-care please let us know. 
-   Pitch your idea / problem
-   Plan a team-skill composition (~5 people)
-   Collaborate!”

This part is targeted at team leaders, and since we are forming the teams it is a bit confusing: 
“100% DIY: Apply with your idea. Recruit an interdisciplinary team. Hack a solution!'”

Let’s think about something more general – also for the diagram (I’m sleepy now so my brain is shutting down) 

*Change NCBI link to: 
https://github.com/NCBI-Hackathons/Resources_for_Designing_Hackathons
- FAQ
  Remove ‘What's a Hackathon?’ and edit 
  “What's hackseq?
  hackseq is a Vancouver-based hackathon - software/hardware development ('hacking') marathon - focused on omics. We want to bring individuals with diverse backgrounds together to collaborate on scientific questions and problems in genomics.
  Our philosophy is open-source, open-notebook, open science.
  Prospective Team leaders will pitch their ideas, teams will be formed and everyone will work together for 3 days to find solutions.”
- Need a section for Partners and Sponsors: For the ones we have and those that would like to be.

**Comment by ababaian** [comment]
Reorganized website. Front page substantially simplified (as it should be).

| genomics
now: *omics
another option: [*]omics

|...also for the diagram 
moved to Participate page where there's a brief explanation of team organization and re-coloured to fit more closely with the website theme.
Do you not like the style of the diagram? What do you have in mind?

| Front page FAQ
Having both 'What is a Hackathon' and 'What is hackseq' I think is good. Not everyone will have heard of a hackathon before and that's a single concept in itself

|*Need a section for Partners and Sponsors: For the ones we have and those that would like to be.
I've added an email link to the hackseq account for anyone interested in sponsoring. Which you can then reply with the sponsorship package

| who are we page
now live, i'll update photos / affil as they come in

"Format" page is really what's left to develop as well as a visual agenda

**Is the website OK to go online as it stands?**

**Comment by adrisua** [comment]
Thanks @ababaian
Diagram looks great!
I got feedback from people, which is always good:
- Rotate the phylogenetic tree so the cluster in purple fits inside the frame.
- Bring the name hackseq down and make it bigger – genomics hackathon could we underneath.  
- Error message ‘The requested social account cannot be found’ is still there (CATALYZING BIO+INFORMATICS section)
- Remove section ‘Format’. In section “Participate” and underneath “hackseq is open to everyone with coding experience. The focus is on empowering students and trainees who want to use their skills and knowledge in a creative new way” add: “*Based on NCBI hackathons” 
- Above the 'Apply' tab, add "If you require childcare to be able to participate, please contact us"

**Comment by ababaian** [comment]
@adrisua  great suggestions
| - Rotate the phylogenetic tree so the cluster in purple fits inside the frame.
Fixed
| -  Bring the name hackseq down and make it bigger – genomics hackathon could we underneath.
Looks good
| -  Error message ‘The requested social account cannot be found’ is still there (CATALYZING BIO+INFORMATICS section)
I can't reproduce this. Can you share a screen shot so I can track this down?
| - Remove section ‘Format’. In section “Participate” and underneath “hackseq is open to everyone with coding experience. The focus is on empowering students and trainees who want to use their skills and knowledge in a creative new way” add: “*Based on NCBI hackathons”
Done, I'll work on a format page but this is less of a priority atm|
| -  Above the 'Apply' tab, add "If you require childcare to be able to participate, please contact us"
I've added this here but this should simply be a question in the application forms.

**Comment by adrisua** [comment]
awesome @ababaian thanks so much!
Let's take it back online :)
Here is the screenshot
[Doc14.docx](https://github.com/hackseq/October_2016/files/180444/Doc14.docx)
Yes, the 'child care' section will be in the application form but I wanted to have it there so people know we are thinking about it. Also, I would like to have a sense of people needs - maybe this will help to collect information for now. 
Thanks again!

**Comment by ababaian** [comment]
@hackseq/steering_committee Website is online. I'll use the ~/website/todo for any stuff anyone would like added. If it's urgent make an issue and I'll get on it.
