### ISSUE TITLE
Tweet about Hackseq and ASHG Travel Awards

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/October_2016#40]
@adrisua and I just finished a teleconference call with some folks at ASHG and their communications team would be willing to retweet us. They would prefer to retweet something that mentions the ASHG Travel Awards. 

@minisciencegirl, could you draft and tweet something that promotes Hackseq and the ASHG Travel Awards within 140 characters? Post the link of the tweet here once it's online. If ASHG don't retweet it within a few days, we can send them the link via email.

**Comment by minisciencegirl** [comment]
Done and tweeted: "Did you know @GeneticsSociety is providing 3 travel grants for #ASHG16 @hackseq participants? Fill out travel award: tiny.url/hackseqpart"

[Updated] https://twitter.com/hackseq/status/748586831617224704

**Comment by GalenWright** [comment]
Tweet looks good, the url is broken though

**Comment by minisciencegirl** [comment]
Really? I tried it on two browsers and they both worked…

**Comment by GalenWright** [comment]
It's not clickable and when you paste it into the browser it doesn't work. Can anyone else confirm?

**Comment by minisciencegirl** [comment]
ASHG already retweeted this tweet as well. 

Let me know if there's anything else - if not, I will close this issue as being dealt with. I will probably schedule another similar tweet next week after the 7/4 long weekend.

**Comment by GalenWright** [comment]
If the link is broken I think we should delete the tweet and DM the ASHG twitter account asking them to retweet the correct link

**Comment by minisciencegirl** [comment]
The link is not broken. If you go into the @hackseq twitter account, click on the tweet, click on the right side of the tweet with the (...), that's the exact link provided when you click on copy tweet.

Additionally, ASHG already retweeted this tweet -- there are 3 retweets from that already. I don't think it makes sense to delete this tweet. Thanks.

**Comment by GalenWright** [comment]
I'm talking about the link to the participant application i.e. tiny.url/hackseqpart

**Comment by minisciencegirl** [comment]
Ahh thanks. Old tweet deleted and new link added.

**Comment by GalenWright** [comment]
Great, thanks
