### ISSUE TITLE
Install requested software

### ISSUE THREAD

**Issue by sjackman** [hackseq/October_2016#41]
- [x] GATK https://github.com/hackseq/hackseq_projects_2016/issues/7
- [ ] MOODS https://github.com/hackseq/hackseq_projects_2016/issues/6

**Comment by BrunoGrandePhD** [comment]
@sjackman: I suppose this is done?

**Comment by sjackman** [comment]
GATK is done. MOODS is a Python package. We'll just install that on the day.
https://github.com/jhkorhonen/MOODS/wiki/Installation
