### ISSUE TITLE
Steering Committee meeting on July 20th @6pm at the Genome Sciences Center

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#42]
@hackseq/steering_committee this is a reminder that we have another in person Steering Committee meeting coming up on July 20th @6pm at the Genome Sciences Centre. 

I have started to draft an agenda for that meeting here: http://pad.software-carpentry.org/hackseq. The meeting notes from the last meeting have been archived here: https://github.com/hackseq/October_2016/blob/master/meeting_notes/2016-06-23.md.

Apologies that I will have to miss the in person meeting again (I will on a plane that evening...). Could you all kindly take notes on the etherpad in my stead?

**Comment by ababaian** [comment]
I have a JISIS from 5 - 6pm so I'll be a little late

**Comment by ababaian** [comment]
Running late with JISIS 0_0 Sorry don't know if I can make the beginning of themeeting
