### ISSUE TITLE
Participant Resources

### ISSUE THREAD

**Issue by ababaian** [hackseq/October_2016#43]
I'll be putting together a resource page for participants. The idea that before/during/after if there are any resources which participants need (info sheets, maps etc...) then they can refer to a single place and find all of them. I'll leave this up as ongoing development.
- Code of Conduct from the other issue (once decided)

**Comment by adrisua** [comment]
@Brittdrog Would you mind adding here the wonderful map you did :) Thanks!

**Comment by Brittdrog** [comment]
@adrisua - sure here is the [map](https://www.google.com/maps/d/edit?mid=1sZaegrYoiuYdD3Ls1Plk7QADPoA)
If you click on the two venue there are some links to accommodation.

**Comment by Brittdrog** [comment]
@ababaian - thanks for adding the map to the participant resources. Can you also add a link to accommodation options near UBC campus (http://suitesatubc.com/#
http://triumfhouse.ca/non-triumf-lab-ubc-rates.php)?
