### ISSUE TITLE
Steering Committee Meeting August (Aug 17th) @5pm at the Genome Sciences Centre

### ISSUE THREAD

**Issue by Brittdrog** [hackseq/October_2016#44]
@hackseq/steering_committee - do we still have an in person Steering Committee meeting scheduled for this evening (Aug 3rd) @6pm at the Genome Sciences Centre?

**Comment by ababaian** [comment]
I'll be able to make it.

**Comment by minisciencegirl** [comment]
I have a really bad cold and won't be able to make it. 

What's on the agenda today? I thought the plan was we would only meet if we need to debate the travel awards? @adrisua

**Comment by adrisua** [comment]
I wont be able to make it today. @santina @sjackman @brunogrande Would you like to meet today and discuss the participant form and/or project-participant pairing? I am waiting to hear from the ASHG about the travel awards and will contact the participants that applied for the award. 
1. Samantha Kohli (ASHG membership: 350078, points = 15)
2. Ritu Chavi (not a member but registered for the conference, points = 12)
3. Whitney Whitford (ASHG membership: 349628, points = 11)
or
4. Fotis Tsetsos (ASHG membership: 322817, points = 7)

**Comment by sjackman** [comment]
I'm able to meet. I haven't yet had a chance to look at the project participant pairing. If we had nothing else signifiant to discuss, we could look at that together in the meeting. We could also cancel the meeting if it's not needed and that's other folk's preference.

**Comment by adrisua** [comment]
As for our next meeting, would August 24th work for everyone? @ttimbers @cloucks Items to discuss then would be the agenda for the event, awards, volunteers, logistics.

**Comment by ababaian** [comment]
Personally I'm gone Aug 19 - 28

**Comment by sjackman** [comment]
I'm available Wed Aug 24.

**Comment by Brittdrog** [comment]
@GalenWright and I can make the meeting this evening, but have a lab function on the evening of the 24th so won't be able to make that meeting.

From our last meeting items that need to be completed in the near future are:
- Get confirmation that all participants are attending
- Assign participants to teams
- Get approval of teams from team leaders
- Tell participants what teams they have been assigned to

Do you think we need to meet to discuss any of these items today? Alternatively @santina could send out emails to participants and get them to fill out the forms by next week and we could schedule another meeting then, if necessary?

**Comment by GalenWright** [comment]
Seeing as we don't have a unanimous decision and it looks like not many of us can make it today, maybe we should call it off and send out a doodle to decide on when the best time for our next meeting is. I can do this tomorrow if necessary

**Comment by BrunoGrandePhD** [comment]
I'm available to meet on August 24th. I talked with Shaun and we agree that we don't really need a meeting tonight, as we were able to rank the participants for the travel awards.

**Comment by Brittdrog** [comment]
OK perfect! @santina will you contact the participants in the meantime and get them to confirm that they are attending so that we can get started on assigning participants to teams? What are we doing about informing travel award applicants of the results of the travel awards? Will this be included in the confirmation of attendance email or will it be a separate email?

**Comment by GalenWright** [comment]
@hackseq/steering_committee I have created a doodle poll for the next meeting:
http://doodle.com/poll/eucqzx46ezen7q3k
Seeing as we didn't meet yesterday, I think we should try and meet sooner, rather than later this month. Please complete the poll by Sunday evening so that we can finalize the date/time. Thanks

**Comment by ttimbers** [comment]
Hi all, just getting back from vacation. Although I'm still away in Ontario for a wedding this weekend and will be back in Vancouver on Tuesday. Will complete the survey before Sunday and be able to better help with things when I am back in town.

**Comment by GalenWright** [comment]
I looked at the meeting poll and the best time/date for everyone is Wed Aug 17th at 5pm. See you all then

**Comment by DCGenomics** [comment]
Will drop in on hackpad for a few.

You guys are awesome!

Ben

**Comment by BrunoGrandePhD** [comment]
@ttimbers, could you set up the agenda for the meeting on Wednesday? Once you do, could you add the following items to the agenda? Thanks!
- Discuss turning down Chipotle as a food sponsor (see discussion in hackseq/October_2016_private#20 for more details). 
- Brainstorm events that would have had food sponsors.

**Comment by ttimbers** [comment]
Will do!

**Comment by adrisua** [comment]
@ttimbers Would you mind also adding [the volunteer/mentor form](https://github.com/hackseq/October_2016/issues/45) to the agenda? Thank!

**Comment by sjackman** [comment]
Hi, all. I'm back from Michigan. I've accepted a list minute invitation to go camping, so I'll miss the meeting this Wednesday. Sorry for the short notice. Now that we have the confirmed list of participants, I'll figure out the team assignments.

**Comment by BrunoGrandePhD** [comment]
I'll be at the GSC, so we can still hold the meeting there.

**Comment by sjackman** [comment]
@ttimbers Please add to the agenda the possibility of publishing the project reports to the F1000Research Hackathon channel. See https://github.com/hackseq/October_2016_private/issues/27

**Comment by ttimbers** [comment]
@hackseq/steering_committee this is a reminder that we have a meeting **today** at **5pm** at the Genome Sciences Centre. I think we need to call Bruno, not Shaun to get in? Bruno, can you please put your contact number on the planning etherpad or send it to us all via email?

Meeting agenda has been drafted, and lives here: http://pad.software-carpentry.org/hackseq. Please feel free to add anything I missed.

**Comment by BrunoGrandePhD** [comment]
I sent an email to everyone with my phone number. Text me when you arrive at the GSC.

**Comment by cloucks** [comment]
Hi everyone, I had planned to make this meeting, but I am feeling overwhelmed with preparation for my thesis defence coming up at the end of the month and won't be able to make it.
