### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#47]
@ababaian Would you mind adding the [logo](https://tourismvancouver.app.box.com/v/BAH20Logos/1/6602782969/53733669713/1) of Tourism Vancouver in the Megabase section? Thanks!

**Comment by adrisua** [comment]
@ababaian also the [one](http://women.acm.org/sites/default/files/data/ACMW-hi-res-logo.jpg) for ACMW in the Kilobase section. Thanks!

**Comment by Brittdrog** [comment]
@adrisua do we need to add GA4GH ($3000) and AWS (I think @sjackman mentioned that they would sponsor the social)?

**Comment by GalenWright** [comment]
Great news about the new sponsorship @adrisua. I'm waiting for the GA4GH to send me there high res logo - I will let @ababaian know when they do

**Comment by adrisua** [comment]
Sure. GA4GH could be in the kilobase or megabase section. I'm not sure about AWS. I sent them an email from the  hackseq account a couple of weeks ago but they haven't replied. If they are providing credits, we should add them anyways.

**Comment by GalenWright** [comment]
Cool - I think we should put the GA4GH in the Megabase section seeing as US$3000 is ~CA$3900, which is close enough to our $4000 threshold, especially given their additional involvement with the event

**Comment by ababaian** [comment]
@Adrisua Is it the  "20 year Be a Host" logos I should use?

Assuming that's the logo it's done.
