### ISSUE TITLE
Steering Committee Meeting (Mid-September)

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/October_2016#49]
Based on the Etherpad, we still need to schedule a meeting for mid-September. Since we've held the past few meetings on Wednesday evenings, we can try skipping the Doodle poll and see if most of us can make it ~~this Wednesday at 6:00 pm.~~ Now trying for Wednesday, September 21st at 6:00 pm. 

**Comment below with your availability.**

@ttimbers: I'll let you take care of archiving the current contents of the Etherpad to the repository. 
## Details (Tentative)
- **Date:** September 21st, 2016
- **Time:** 5:30 pm
- **Location:** [Genome Sciences Centre](https://goo.gl/maps/rAQdBVz9iSH2)
## Agenda

[Hackseq Meeting Etherpad](http://pad.software-carpentry.org/hackseq)

**Comment by ttimbers** [comment]
@brunogrande - thanks for taking charge on this (I've been overwhelmed with the students starting last week). Will take care of the archiving now. 

I have to be at home that evening caring for a sick animal (my cat had surgery this week), but I can attend remotely via Skype/Google Hangout.

**Comment by BrunoGrandePhD** [comment]
I'm aware that @minisciencegirl can't make it, as she's in England. 

@minisciencegirl: Any chance you can Skype in (which would be at 10:00 am on Thursday)?

**Comment by BrunoGrandePhD** [comment]
@ttimbers: I can only imagine the crazy rush with kicking off a new program. Happy to help!

**Comment by BrunoGrandePhD** [comment]
I'm also aware that @santina has a council meeting with iGSN and won't be able to make it.

**Comment by ababaian** [comment]
Can't make this Wed :( This week is a bit crazy. I'm also gone and out of contact Sept 26th - Oct 8th so if there are website things that need to be done before then please let me know.

**Comment by ttimbers** [comment]
2016-08-17 meeting notes have been archived [here](https://github.com/hackseq/October_2016/blob/master/meeting_notes/2016-08-17.md). An agenda has been started for the next meeting. Feel free to add/edit it. It lives [here](http://pad.software-carpentry.org/hackseq).

**Comment by GalenWright** [comment]
Hey, @Brittdrog and I also can't make it this week - we have an application due this Thursday. Seeing as most of us can't make it, how about moving the meeting to the following week?

**Comment by BrunoGrandePhD** [comment]
@hackseq/steering_committee: Comment below if you are available to meet next week on Wednesday, September 21st at 6:00 pm. Thanks!

I would be able to make it.

**Comment by BrunoGrandePhD** [comment]
@ttimbers: Thanks!

**Comment by GalenWright** [comment]
21 Sept works for @Brittdrog and me

**Comment by sjackman** [comment]
I'm not able to attend Wed Sep 21 at 6pm. I rehearse with my choir on Wednesday evenings at 7pm.

**Comment by ababaian** [comment]
I can make time any evening next week except for Thursday.

**Comment by cloucks** [comment]
I am available any evening next week.

**Comment by BrunoGrandePhD** [comment]
@sjackman: Would starting the meeting at 5:30 pm give you enough time to make it for your rehearsal? If not, how about 5:00 pm?

**Comment by sjackman** [comment]
I'd have to leave at six o'clock. Either start is fine, depending on how much time people need to get here. I'll leave when I need to and everyone else can stay.

**Comment by minisciencegirl** [comment]
I can make it next Wednesday. But I would prefer if we could meet at 5:30pm so that I have enough time to get from UBC to Genome Sciences.

**Comment by BrunoGrandePhD** [comment]
Okay, let's go with 5:30 pm to give everyone time to arrive. We'll discuss things relevant to Shaun in the first 30 minutes before he leaves.

**Comment by santina** [comment]
I'm also available next Wednesday. Thanks!

**Comment by adrisua** [comment]
I'm also available on the 21st

**Comment by BrunoGrandePhD** [comment]
It seems like a majority of us can make it on **Wednesday, September 21st at 5:30 pm**. Let it be known that the date and time is now official! See you all next week!

**Comment by sjackman** [comment]
I wasn't able to arrange childcare for the meeting this Wednesday. Sorry. I'll participate remotely if someone can Facetime me in.

**Comment by ttimbers** [comment]
@sjackman - we can do that!

**Comment by ttimbers** [comment]
@brunogrande - what time is the meeting today? In the issue it says both 5:30pm & 6:00pm? On the etherpad it says 5:30pm? So I assume 5:30pm?

**Comment by sjackman** [comment]
I'm ready to Facetime in whenever you're ready.

**Comment by ttimbers** [comment]
I'm fairly useless with facetime - gonna try to get you on a Google Hangout

**Comment by sjackman** [comment]
I just tried calling you with Facetime and Google Hangouts without any luck. Try calling me?

**Comment by ttimbers** [comment]
@sjackman I failed at Google hangouts and facetime - do you have skype?

**Comment by ttimbers** [comment]
no - the internet is terrible

**Comment by sjackman** [comment]
Liz is here now. I'll come by in person. I'll have about fifteen minutes before I have to leave.
