### ISSUE TITLE
Volunteer introductions

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#52]
Hello! Thank you so much for expressing your interest in volunteering for hackseq. It's gonna be busy and bustling. 

Things we'll mostly likely need assistance with: 
1. Setting up, for example, carrying food and moving furniture
2. Assist people with technical support. There will be some people who are unfamiliar with Git, command line, and other tools. 
3. Administration and logistics, for example, signing in, making sure things are communicated, people know where to go, answering questions. 
4. Helping out with specific projects, especially when people unfamiliar with the technology need to ramp up. 

This list is not conclusive. We'll be running into many issues and tasks as the hackseq event unfolds. Since we'll all be working closely together to make this event successful, **please introduce a bit about yourself, tell us what you'll like to help out with, and other technical knowledge that you want to share with the participants, and include some questions if you have any**. 

We already got your availabilities if you responded to the volunteer form, but feel free to include it if your schedule has changed. 

Thank you and we look forward to meeting you!

**Comment by santina** [comment]
To start, I'm Santina, a bioinformatics master student. I do all my work on the computer, so I always look for opportunities to look away from screens!  I enjoy hiking, eating, playing games and learning new things.  Ask me questions about things to do in Vancouver! ☀️ 

I can help out with general logistics and ramp up any people who need a refresher or a crash course on things like command line, Git, Python, R, etc.

**Comment by LeungConnie** [comment]
I'm Connie, a PhD student studying obesity and diabetes. 

I can help with Administration and logistics!

**Comment by eringill** [comment]
I'm Erin, a research associate in the Microbiology and Immunology department at UBC. I analyse RNA-Seq data and clinical metadata to identify potential drug targets and study factors that are indicative of disease severity.

I can assist with any and all of the items listed above. Specifically, my computational expertise lies in the use of command line, R and python.

**Comment by dfornika** [comment]
Hi, I'm Dan. I work at Fusion Genomics, where I work on infectious disease assay development. I split my time between the wet lab and computation. I'm currently developing a web app to track the production of our sequencing libraries.

I'll be participating in HackSeq on Team 9. Outside of my team responsibilities, I'll be happy to help out with setup and admin stuff. I've volunteered at Software Carpentry Bootcamps on git, python and R, and would be happy to help out with quick beginner-level troubleshooting.

**Comment by lstmemery** [comment]
Hey there. My name is Matthew Emery and I'm a graduate student in Data Science, former Python software developer with a background in biochemistry. 

I can help with set up and tech support.

**Comment by rollingDough** [comment]
Hi everyone, I'm Minh. I'm an undergraduate student major in Management Information System. I look forward to working with all of you!

**Comment by ananab** [comment]
Hi guys. My name is Kai He and I'm currently a Master of Data Science student. My undergraduate study was Biochemistry with a Minor in Math. 

I can help with setting up, tech support, and signing in.

**Comment by zhaoxiaofei** [comment]
Hi guys. I am XiaoFei. Please don't be upset if you will mispronounce my name :D I am working at Fusion Genomics as a computational biologist. For my work, I am developing computational tools for the typing of infectious diseases, assisting in the development of web portal for the management of data and projects, and analyzing NGS data.

I can help with tech support, set up of coding environment, any computer-related stuff, etc. I especially have a lot of coding experience, so feel free to ask me any question related to coding.

**Comment by irobii** [comment]
I'm Ka-Kyung, a postdoctoral fellow in Translational Genomics Informatics Lab at Severance Biomedical Science Institute. I'm doing translational disease-mutation analysis, visualization, and integration for multiple investigators and research projects with NGS data. I'm currently focusing an integrative analysis of whole genome and whole transcriptome sequencing in inherited brain disease.

I can assist with any of the items listed above. Especially, I hope my experience on integrative WGS and RNA-seq study would be helpful in project#4 (Pseudo-WGS variant calling for common cell types aggregating ChIP-seq, RNA-seq and DHS from ENCODE and Roadmap Epigenomics data).

And, I have a question. Can I book accommodation of Suite UBC or Triumf which is posted at 'http://www.hackseq.com/participant-resources'? (or I'm looking for room mate during hackseq 2016).

**Comment by lfunderburk** [comment]
Hello everyone!

My name is Laura. I am currently a Co Op student working at BCCRC IT. I have taken workshops on Git, Command line and Python thanks to Software Carpentry and have experience setting up and providing people with tech support. I would be happy to provide both skills during this weekend :).

-Laura

**Comment by santina** [comment]
@irobii : You can stay wherever you want. The recommendations we gave on the website are places that are on UBC campus, so you can travel easily between where you're staying and hackseq's location. You can definitely arrange to room with someone as well :).  I'll be adding you to the hackseq channel so you can ask if anyone is still looking for accommodation! 

@irobii  I'll also add you to the project 4 channel once they set that up.

**Comment by daisieh** [comment]
Hi! I'm Daisie Huang and I'm a fairly frequent instructor for Software Carpentry. I usually teach Git and sometimes Python. I used to be a postdoc at UBC, working on phylogenomics in Populus. Currently I am a freelance scientific software developer and I primarily work for Dryad Digital Repository.

I would be happy to help with anything that needs doing!

**Comment by santina** [comment]
Awesome! I've invited you guys to join the hackseq slack channel. Please also download the slack app on your phone (it'll probably prompt you if you open the invite link in the email on your phone). We'll be using that to communicate during the event. I'll be assigning the time slots in a bit.

**Comment by radaniba** [comment]
Hi 
I am Rad, senior bioinformatician at bc cancer agency / UBC
Although I would like to help with all programming issues, which I would do with great pleasure, I think I will bring my camera and take pictures of this event which will take me a bit away from computers for the weekend :) if you need a photographer, am in :)

**Comment by santina** [comment]
@radaniba Yes!! We do need a photographer. Thanks for offering that :D

**Comment by santina** [comment]
Hi everyone, as discussed in #55 , we are having the last planning meeting tomorrow at **5pm** at UBC, at the site of hackseq to go over the last todo logistics items as well as going through some run-throughs. The address is: 
2350 Health Sciences Mall, Vancouver, BC V6T

If you're in Vancouver, please come join us ! :)
