### ISSUE TITLE
Reception Mon Oct 17

### ISSUE THREAD

**Issue by oneillkza** [hackseq/October_2016#53]
@adrisua and/or @sjackman, Angel was asking me if there was an alternate way of getting in touch, since you hadn't replied to his email from Sunday as yet. I've sent an email suggesting some options for a reception, which I'm hoping might take some of the load off that for you guys. Anyway,  if you could get back to him, that would be awesome!

**Comment by sjackman** [comment]
See https://github.com/hackseq/October_2016_private/issues/38 for e-mail communication so far.

**Comment by oneillkza** [comment]
Awesome! I can't read that, since it's private, but as long as you got back to him!

**Comment by sjackman** [comment]
I haven't responded to Angel yet. I'm going to call Steamworks first and find out what the minimum spend is for the evening of Mon Oct 17. Is the head count ~100 people?

**Comment by sjackman** [comment]
I spoke with Sujitha at Steamworks. The largest room is booked for that evening.

The Harbour room standing capacity is 75. The Wine room standing capacity is 50. The rooms are adjacent and connected. The standing capacity of the two rooms is 125.

The Harbour view room minimum spend is $2000. The Wine room minimum spend is $800. The total minimum spend is $2800.

**Comment by adrisua** [comment]
Yesterday we decided to have the social in a pub, instead of hosting it at LSI. @ttimbers is checking options on campus. I will email Angel to let him know that we are looking for venues. Thanks @oneillkza!

**Comment by oneillkza** [comment]
No worries!

Yeah, looks like Steamworks will be quite a bit more than Angel's budget, so wouldn't work unless you guys could get matching funding. On this note, the money Angel can put down will be enough for a drink or two each, but not really for food. So unless there is additional money to put into this, it'll have to be an after-dinner event. (If you can get more funding, I'd suggest doing something like the other funding pays for cocktail food, while AWS sponsors the first round or two of drinks.)

Re: venue:

At UBC, there aren't a lot of bars that could host that many people, but I'd start with the Pit Pub or the Gallery.
http://www.the-pit.ca/
http://www.ams.ubc.ca/foodanddrink/gallery-2/

The Gallery has an impressive view, but may be too small, so best to ask; the Pit is bigger but is in the basement / has more of a nightclub feel.

Alternately, the LSI has large common spaces, so it would be pretty viable to do a catered party there. This has been done before after various research days.

**Comment by adrisua** [comment]
@oneillkza We don't have additional funding for this. Do you have more info about catering options that we could use at LSI? If we go with LSI, we will have to start applying for a liquor license soon @minisciencegirl @ttimbers thoughts?

**Comment by oneillkza** [comment]
I'll copy/paste from my email in the other thread:

_Option 2_:

Have a catered reception with bar service at the LSI at UBC
http://catering.ubc.ca/our-menus/beverage-menu/

Advantages: On-site for the hackathon, minimal effort

Disadvantages: Similar to Steamworks re quantities; bar service may
actually end up more expensive than Steamworks

_Option 3_:

Beer and pizza at LSI at UBC, with volunteers with Serving it Right,
eg myself or Amy Lee doing the serving

Advantages: We could get a lot more beer/wine and food; LSI is at the
Hackathon venue

Disadvantages: We need to buy the beer; someone needs to stay sober to serve it, need to sort out big tubs of ice/some kind of cold storage

Note that it if you're looking at getting a catering service, it'll just be a bar for that money. I don't think there'll be budget for catering service food. If you want to feed people, pizza is pretty much the only thing that would work, which going by VanBUG experience would cost in the region of $500 for 100 people. You could probably also do some kind of combination, like a bar service from the caterers (with everyone getting one free drink ticket, then cash after), and pizza. That would feed everyone and not require volunteers for the bar.

**Comment by sjackman** [comment]
The minimum spend is before tax (7%) and gratuity (18%), so the minimum spend is $3,500. If we have 100 people, $3500 is $35 per head. With AWS contributing $10 per head, can we ask each participant to pay $25 for dinner+drinks? That'll meet the minimum spend, and would be enough for one drink + appies (maybe enough for a meal) per person.

**Comment by sjackman** [comment]
A meal's worth of appies (10 pieces per person) is roughly $25 + 25% = $31.25 per head.

**Comment by oneillkza** [comment]
Yeah that would work. I don't believe Steamworks would do a le carte for 100 people, but they do have a reception menu, which would be effectively the same thing (about 10 canapes per person for $25 each)

http://steamworks.com/sites/default/files/SW_Reception_Menus-NEW.pdf

You could then do the drinks ticket thing -- first drink is on Amazon, cash bar after. 

One minor downside is that you'd almost certainly have to pay this as a lump sum to Steamworks (or pay the Amazon part on Angel's credit card, and the remainder from Hackseq). They definitely won't process 100 people's individual payments for you, so you'd have to get them to buy tickets. However, something like Eventbrite would work for this.

**Comment by minisciencegirl** [comment]
@adrisua: Applying for liquor license could be done up until a few days before the event. However, purchasing enough beer and serving beer for 100 people could be challenging. @oneillkza for VanBUG, I think we typically deal with ~40-50 people on average, with only about 20 - 30 people drinking. I wonder if we would need more than 2 servers to man this event properly?

If we are going with the Steamworks/ Pit/ other bar option, we should definitely put up the Eventbrite site ASAP to get rough numbers. Potentially by hosting the event at Steamworks, maybe we won't have as many people show up?

**Comment by sjackman** [comment]
@oneillkza Surprisingly, I believe Steamworks will handle a cash bar for 100. Would have to confirm.

Sujitha Shivajothi at Steamworks wrote…

> For beverages, we bill on consumption. We are flexible with how you would like to run billing at the bar (open bar, limited bar, drink tickets, cash bar, etc.)

**Comment by sjackman** [comment]
Sujitha Shivajothi at Steamworks wrote…

> Thank you for your inquiry. At this time, I have our Harbour View Room and Wine Room available at Steamworks on Monday October 17th. The Harbour View Room has a private bar and can seat up to 60 for a banquet dinner, 50 for a buffet or hold 75 for a standing reception. The Wine Room can hold up to 50 for a standing style reception.
> 
> To book the space, there is no rental fee but rather a food and beverage minimum spend of $2000 before tax and gratuity on a Monday evening for the Harbour View Room and $800 for the Wine Room.
> 
> To confirm a booking, we require a deposit of half the minimum.  It is not applied to the bill on the evening but is refunded on the business day following given that the minimum spend has been met.
> 
> For large parties, we require that you order from our group menus with combined billing for food. I have attached our menu options for hors d’oeuvres. Please note with our canape list there is a minimum order of 25 pieces per canape selected as well as a minimum of $20 per person.
> 
> Menu selection and final guest count is required at least 3 business days before your event. The food bill is subject to GST and 18% gratuity. We will charge you for the greater of the confirmed guest count or actual attendance.
> 
> For beverages, we bill on consumption. We are flexible with how you would like to run billing at the bar (open bar, limited bar, drink tickets, cash bar, etc.)

**Comment by sjackman** [comment]
@minisciencegirl wrote…

> If we are going with the Steamworks/ Pit/ other bar option, we should definitely put up the Eventbrite site ASAP to get rough numbers.

:+1:

> Potentially by hosting the event at Steamworks, maybe we won't have as many people show up?

My guess is that a number of Hackseq people may stay downtown if that's where there hotel is for the ASHG meeting.

**Comment by oneillkza** [comment]
@minisciencegirl Yep, this crossed my mind too. For the year end party we've tended to have 2 servers, though we did tag team it a bit, and the numbers were closer to 50. That said, I have helped serve at a departmental holiday party with about 100 attendees, where most people were drinking. The way we did that was to have 3-4 servers for the first hour (to deal with the initial drinks rush), after which most of the early servers went "off shift", leaving 1-2 servers for the rest of the event. That worked fairly well. Again, though, there is a requirement to find a few people with SIR, and at least one person who won't drink at all.

@sjackman Ah, thanks for posting the email! Yes, that's what I was trying to get at, they'd do cash bar for drinks, but combined billing for food (so pre-purchasing tickets for food would be necessary).

Numbers are also going to be tricky; if not everyone decides to come, the Harbour room may be large enough. It might be worth only booking the Harbour room at first, and not booking the Wine Room unless the number of people buying tickets goes over 75. The risk would be that the Wine room may become unavailable if more people did want to come.

Another option would be to assume that not everyone would buy tickets, and limit them to 75, but that could be exclusionary.

**Comment by sjackman** [comment]
I like Amy's suggestions. Let's create an Eventbrite event, e-mail the participants pointing out that there is limited room, sell tickets at $25 CAD (?) for food and one drink, and see how many responses we get. If we break 75 people in say less than a week, we can book the other space (if it's still available). If not, cap the event at 75 people. The event coordinator at Steamworks may give us first refusal on the second room (that is, call us before they book it for someone else).

**Comment by oneillkza** [comment]
ASHG is being held at the Convention Centre, so most people will likely be in nearby hotels, or hotels with easy Skytrain access.

**Comment by adrisua** [comment]
@minisciencegirl @cloucks Would you mind setting up the eventbrite and advertise?

**Comment by adrisua** [comment]
I was thinking that $25 might be steep for students. Maybe we could have student tickets for $15?

**Comment by oneillkza** [comment]
This is true, but the only ways to do that (if it's at a bar) would be:
1.  Find external funding to cover the shortfall (or increase non-student tickets to $35?)
2. Make all the tickets $15, but no free drink tickets. (ie Amazon subsidises the food instead of the drink).

**Comment by sjackman** [comment]
Jasleen Grewal wrote…

> Hi Shaun
> Realised that I was supposed to send this along to you at some point, reg organizing the ASHG/hackseq social event? So I was basically in conversation with Lindsay, she is the outside group sales coordinator at Steamworks/Rogue. She is super nice and helpful with organizing everything, and I think the Rogue Convention Centre location will be quite appropriate for the ASHG stuff too. Here's Lindsay's contact email - Lindsay Mroch | Rogue Convention Centre lindsay@roguewetbar.com
> Let me know if I can help in any other way! 
> Cheers,
> Jasleen.

I'll contact Lindsay and get pricing for Rogue Wet Bar.

**Comment by sjackman** [comment]
> Make all the tickets $15, but no free drink tickets. (ie Amazon subsidises the food instead of the drink).

That doesn't unfortunately reduce the ticket price. The minimum spend is $2800 + 25% = $3500, less the $1000 AWS contribution is $2500, which is $25 per person based on 100 people. The minimum spend and ticket price is not affected by whether we spend it on food or drink.

**Comment by sjackman** [comment]
> Find external funding to cover the shortfall (or increase non-student tickets to $35?)

Charge $20 for students and $30 for non-students? A fifty-fifty mix of both means we'd break even.

**Comment by minisciencegirl** [comment]
All of this is dependent on whether we can sell 100 tickets. If we don't, we will still be stuck with the $2500 bill. 
As much as I am not keen on Option 3 due to logistic complications, this may be our only financially viable option.
@oneillkza: do you know any other person with SIR who you can potentially persuade to help out?

**Comment by ttimbers** [comment]
If we are thinking downtown, near the convention centre is good, we held a student conference social last year for drinks & food for 100 for $2500 from Mahony & Sons (Stamps Landing location, at convention centre).

For $2500, we got 50 beer, 50 wine and 50 orders of canape menu A (below).

![screen shot 2016-09-25 at 10 37 45 am](https://cloud.githubusercontent.com/assets/6865016/18817079/33e9f94e-830c-11e6-8795-53540d3c0fbd.png)

Elephant and Castle downtown also had similar prices... This would save us $1000 from holding it at Steamworks, assuming the prices are the same this year.

We could then sell $15 tickets for the event? I agree Eventbrite is the way to go to sell them. What do people think of this option? Should I get us a quote for this year? Or should we go with the LSI?

**Comment by sjackman** [comment]
My preference is a downtown venue if we can make that happen. Please do get a quote from Mahony and Sons, and I'll get a quote from Rogue tomorrow.

**Comment by sjackman** [comment]
I wrote…

> Hi, Lindsay. Jasleen Grewal from the BC Cancer Agency Genome Sciences Centre put my in touch with you and said you've been helpful in booking student-run events.
> 
> We'd like to host a stand-up reception for an estimated 100 people the evening of Mon Oct 17. We'll be buying appies and one drink per person from presale tickets, and then a cash bar for additional drinks. One of the downtown locations would be preferred, but I'd be interested in a quote for the Broadway location as well. What rooms do you have available that evening with what capacities, and what is the minimum purchase?
> 
> Cheers,
> Shaun

**Comment by sjackman** [comment]
Lindsay Mroch at Rogue wrote…

> - Rogue Gastown, The Platform, standing capacity 80, $1500 + 25% = $1875
> - Rogue Convention Centre, Dining Room, standing capacity 80, $1500 + 25% = $1875
> - Rogue Convention Centre, Terrace, standing capacity 65, $1000 +25% = $1250
> - Rogue Convention Centre, Tourism Vancouver, standing capacity 80, $2500 + $450 rental fee + 25% = $3687.50
> - Rogue Broadway, Dining Room and Lounge, standing capacity 150, $4000 + 25% = $5000

So long as we're happy with a max capacity of 80 people, both these venues look good:
[Rogue Gastown, The Platform](http://www.roguewetbar.com/gastown/group-events/the-platform), standing capacity 80, $1500 + 25% = $1875
and
[Rogue Convention Centre, Dining Room](http://www.roguewetbar.com/conventioncentre/group-events/dining-room), standing capacity 80, $1500 + 25% = $1875
The ticket price per participant would only be $11 each for 80 people after the AWS $1000 contribution.

Note that $11 (including tax and tip) per person wouldn't buy much food, roughly 3 canapes per person, but it would keep the fixed ticket price done. We may want to consider rounding the ticket price up to $15 so that we can order a bit more food. It still wouldn't be enough for a full meal, I don't think.

I've asked whether we can combine adjacent rooms to accommodate more than 80 people.

**Comment by sjackman** [comment]
I have seen _Rogue Gastown, The Platform_ in person. It's up a set of stairs looking down over the main restaurant. It's a nice space, but it looks like it may be more appropriate for a sit-down dinner, unless the tables can be moved.

I haven't seen _Rogue Convention Centre, Dining Room_ in person. From the photo it looks like a nice open space.

Does anyone work in Gastown who would be able to check out this space in person?

I'm thinking that we should book one of these two spaces. Is a capacity of 80 enough?

**Comment by adrisua** [comment]
I think capacity of 80 is good. 

If we sell tickets on eventbrite, is there an account we could use (maybe from VanBug) or do we have to create a new one? Another option would be using SCWIST's account but I would need to ask if that is possible.

**Comment by sjackman** [comment]
Great. If we agree on the venue, we'll need about $1000 for the deposit. Do we have cash available?

> To confirm a booking, we require a deposit of half the minimum. It is not applied to the bill on the evening but is refunded on the business day following given that the minimum spend has been met.

**Comment by oneillkza** [comment]
VanBUG unfortunately does not have an Eventbrite account -- you'll need to set one up yourselves or use the SCWIST account.

**Comment by sjackman** [comment]
Lindsay Mroch at Rogue wrote…

> My two suggestions would be either the Rogue Convention Centre Dining Room - Standing 85-90 with a minimum spend of $1500 + taxes and gratuity or The Platform + East Side Lounge at Rogue Gastown - Standing for 115 with private bar with a minimum spend of $2200 + taxes and gratuity.  Either space will work great for a group of your size.  It's rare that all 100 guests will be present at the exact same time so having a alightly smaller space should not be an issue if you are leaning towards the Rogue Convention Dining space.  
> 
> I hope that this helps to narrow your search.  If you would like to discuss your options or placing a hold on eihther of the spaces please feel free to contact me at any time.
- The _Rogue Convention Centre Dining Room_ standing capacity is 85 to 90, not 80 as I said earlier. $1500 + 25% = $1875
- The _Rogue Gastown The Platform_ can be combined with _Rogue Gastown East Side Lounge_ for a combined standing capacity of 115 with a private bar for $2200 + 25% = $2750. _The Platform_ alone has a standing capacity of 80.

The latter option is nice if we want to start by booking _The Platform_ and expand to include _East Side Lounge_ if we get more people than we expect, assuming that _East Side Lounge_ doesn't get booked.

Shall we put a deposit down on one of these two spaces?

**Comment by sjackman** [comment]
I wrote…

> I've been to Rogue Gastown, but I haven't yet been to Rogue Convention Centre. Which space, in your opinion, is better suited to a standing reception, and which is the more attractive or has a better view?

Lindsay Mroch at Rogue wrote…

> For the best view I would come to rogue convention centre. We have an unobstructed view of the harbour and north shore mountains, it really is lovely. I will send you some photos in a moment when I return to my desk.

**Comment by adrisua** [comment]
I asked if SCWIST could pay directly. We might need an invoice from them though. As for the eventbrite, I already asked if we could use SCWIST's account. Let's start brainstorming content (text and graphics). Let me know if you have ideas.

**Comment by ttimbers** [comment]
So we are going with Rogue, yes (looks good to me too)?

**Comment by sjackman** [comment]
The _Rogue Convention Centre Dining Room_ sounds like the best venue if we're happy with a standing capacity of 90. Let's take a look at the menus, decide how much food we want to order, and determine the ticket price. Should there be enough food that this should be a complete meal? If so I'm thinking about $20 per ticket, which is $16 before tax and tip. That might be a bit on the light side, but as long as folk aren't starved, they could always find more food afterward.

**Comment by sjackman** [comment]
Here's a photo of _Rogue Convention Centre Dining Room_.

![rogue cc dining room](https://cloud.githubusercontent.com/assets/291551/18922370/2ba3219a-855d-11e6-8d2d-12e981e594e9.jpg)

**Comment by adrisua** [comment]
Eventbrite charges 3.5% of the ticket cost plus C$0.60 per ticket sold in Canadian dollars. 

We have two weeks to sell 90 tickets at $20 each. We need a really good marketing strategy to push them. Maybe making someone famous to come?

**Comment by adrisua** [comment]
SCWIST's bookkeeper wrote: 

> Please ask for an invoice.  I won't be back in the office until October 5th and will print the ck then

**Comment by ttimbers** [comment]
This seems like us doing a lot of work to try to make a good event we don't really have the funding for... I don't think participants want to buy a ticket to an overpriced event (this seems like our options...). I don't mean to be a debbie downer, but I wouldn't buy a $20 ticket for a single drink and an appie or two... 

Can we squeeze any more money out of our budget to reduce the ticket price? If not, can we scrap the event? Or does AWS have a hotel room where we could host an informal party and just have beer/wine there (I know this sort of thing happens at other conferences)?

Or maybe our social on Saturday night is enough, and we can say thanks Amazon, but no thanks. We just have too many people for the small budget?

**Comment by sjackman** [comment]
I'm hoping that most participants would want to come to the social on the last evening. Twenty bucks seems pretty fair to me for dinner and a drink. You'd spend that on dinner no matter where you ate in Vancouver. Twenty bucks per person would buy 5 minibugers per person (for example, we'd get more variety than just sliders), which to me seems like enough for a full meal. The minimum that we could charge per ticket and still meet the minimum purchase would be $10, but I'd be afraid that there wouldn't be much food per person.

I suggest that we poll the participants and get an estimate of how many people would be interested in coming to the social if the ticket price were $20.

If we want to scale back, I suggest we go to a pub on campus, AWS can hand out drink tickets as they like, and let everyone fend for themselves food wise. I'd prefer not to decline AWS's offer this late in the game. Free money for the social seems like too good an offer to pass up.

**Comment by ttimbers** [comment]
I like the idea of a poll to the participants. I think that would really let us get a better handle on actual numbers. Some people just don't like pub events, regardless of the cost, and others might have personal/family/work obligations on a Monday night.

**Comment by minisciencegirl** [comment]
Sorry to pipe in late here. I just called Joe at the Pit, who also manages Gallery. I know we are not keen on having it on campus, however both Pit and Gallery do NOT have a minimum spend.

For Pit, they can host up to 400 people. On Monday, there's Trivia Night going on. They would be willing to fence off an area just for the hackathon. At the Pit, there is only Pizza, but drinks cost $5 - $6. So we can easily do 100 drinks, and maybe some pizza. Pit doesn't open until 7PM, but Joe is willing to open the bar at 5PM for us.

For Gallery, drinks are more expensive, but there's more food options. Drinks cost $6-7. Kitchen closes at 7pm. Bar stays open for as long as people around.

This is another option without having to worry too much about selling minimum number of tickets.

**Comment by sjackman** [comment]
Both of these seem like good options. Nice find, Amy! If a lot of people express interest, do we want to preorder dinner? I'm afraid if we just come in unannounced and order 80 dinners, it could take hours to get the food out.

**Comment by minisciencegirl** [comment]
That sounds reasonable. I could email Joe to see if we can have a preset menu for Gallery and have people pay for the food themselves? We can get a rough count of people at the start of the hackathon and I can let Joe know the total number?

For pizza at the Pit (they have no other options), we can do a rough count to figure out how much we can pay with our current budget.

I have our event tentatively circled in for the date and can ask Joe to send us a final quote/ confirmation in writing if we all agree with this plan?

**Comment by oneillkza** [comment]
Both the Pit and the Gallery should also be able to use AMS catering to get quite a range of meal options. I'd expect they'd need some kind of confirmation of numbers at least a few days beforehand, but that should be fairly doable?

I'd suggest the Gallery over the Pit, mainly because it has a view and a really nice space, while the Pit is in the basement.

**Comment by adrisua** [comment]
@minisciencegirl great options! Once you confirm please let me know, so I can email LSI and tell them we wont be needing a liquor license after all.

**Comment by minisciencegirl** [comment]
In that case, looks like most people on this thread prefer Gallery. People can deal with food and we will get a rough count for Joe a few days prior.

**Comment by sjackman** [comment]
After getting Joe the headcount, when should we get him the exact meal orders? Same time as the headcount, or earlier the same day of the dinner?

**Comment by GalenWright** [comment]
Our gmail is getting emails every time someone signs up for the social. @adrisua do you have access to the Eventbrite account - if you do, can you please turn off this notication? Details copied from the related email below. Thanks

> P.S. You can turn off this notification anytime on your email [preferences page](https://www.eventbrite.com/email-preferences?utm_source=eb_email&utm_medium=email&utm_campaign=order_confirmation_email&utm_term=orgbccemailpref&ref=eemailordconf).

**Comment by minisciencegirl** [comment]
@GalenWright: Thanks. Notification is turned off.

**FYI for Saturday's event at the Pit**: "please note that the PIT event on SATURDAY is a 19+ only venue so you'll have to limit invites to only those of legal drinking age. 
Unfortunately the Pit is a Liquor Primary Licence and these are the rules / laws.  Thank you for understanding." @adrisua if you could make an denouncement to that effect on Saturday, that will be great.

**Comment by GalenWright** [comment]
Thanks @minisciencegirl
