### ISSUE TITLE
Logistics

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#54]
[Here](https://docs.google.com/spreadsheets/d/1od5J4I_Rbtqx-A4PEJOmDW7EZfqPXumYGg2iiibSv1U/edit#gid=501875787) is a list of things we need including food. Feel free to edit.

**Comment by adrisua** [comment]
@Bruno Would you be able to contact Raymond from IT services (604.822.2008) today or on Monday to check our options with wifi? This is what he wrote to Mandeep from Ecoscope:

> If ubcvisitor is not suitable, an event-specific SSID/network can be configured.
> Authentication can be either be by a single shared key or by web authentication redirect pages.
> This solution requires advanced notice so that it can be configured.
> There is a fee associated with requests such as these.
> Raymond 
> Support Analyst 
> IT Service Centre, UBC
> Tel: 604.822.2008 
> http://it.ubc.ca/support

Thanks!

**Comment by BrunoGrandePhD** [comment]
I requested access to the Google document. 

I also contacted UBC IT via the phone. They offered three possible solutions:
- Have users use ubcvisitor (but this network has limited bandwidth and some ports are closed).
- Have UBC IT create temporary accounts fort ubcsecure (not feasible for 100 users).
- Have UBC IT create a temporary network just for Hackseq for the duration of the event. 

We would need to go with the third option. The estimate I got over the phone was $500-800, but the IT person insisted that this was a ballpark figure and that we should open a ticket to get an official quote. I'm just hoping that the cost doesn't depend too much on the duration of the event. 

I created the following ticket at the [UBC IT website](http://web.it.ubc.ca/forms/isf/). 

> Hello, 
> 
> I am one of the organizers of an event that will be hosted at UBC. The event is the Hackseq Genomics Hackathon. It will take place at the Life Sciences Institute on October 15 to 17, 2016. We expect to host around 110 people, most of which will not have UBC login credentials. 
> 
> Given the nature (hackathon) and size of the event, the limited bandwidth and closed ports of ubcvisitor will not be suitable for us. Moreover, creating over 100 temporary accounts for ubcsecure is probably not feasible for UBC IT. 
> 
> Another option that we were offered is the creation of a temporary Wi-Fi network (with a separate SSID) for the duration of the event. My understanding is that there would be a shared password for this temporary network. Please correct me if I'm wrong. This seems to be the most appropriate solution given our needs. 
> 
> This ticket is to begin the process of setting up such a network for our event. What would be the fee associated with this request?
> 
> Thank you, 
> Bruno Grande
> On behalf of the Hackseq Organizing Committee

**Comment by GalenWright** [comment]
Thanks @brunogrande - I saw that you requested access via google and changed the sharing preferences and everyone should be able to edit now

**Comment by adrisua** [comment]
@brunogrande Thanks! Do you think it would be possible to inquire for a reduced fee? Ecoscope is one of our main partner and almost half of us are affiliated with UBC.

**Comment by BrunoGrandePhD** [comment]
@adrisua: I will inquire about a reduced as fee as soon as UBC IT respond to the support ticket. As far as I can tell, this hasn't happened yet.

**Comment by BrunoGrandePhD** [comment]
Note to self: compile the list of food restrictions based on the responses to the Confirmation of Attendance form.

**Comment by BrunoGrandePhD** [comment]
UBC IT responded to my ticket this morning. 

> Hi Bruno,
> 
> We can set up a separate SSID for your event, we have done this before for other similar events on campus. Are you going to be in one of the atriums in Life Sciences? Can you please give me a more specific location? Before I give you an estimate for the service I would like to check and see if the area will require additional temporary access points to provide enough coverage for your group.
> 
> Thank you,
> Sarah

My response:

> Hello Sarah, 
> 
> Our main event will take place in the LSI East Atrium. We will also be using the LSI rooms 1330, 1410 and 1416 sporadically throughout the event for breakout workshops. 
> 
> Note that UBC Ecoscope is one of our main partners for the event and most of the organizers are affiliated with UBC. As we are completely self-funded, we would appreciate and benefit from any discount on the regular fee that can be offered for this type of request. Let us know if this is in any way possible. Thank you!

**Comment by BrunoGrandePhD** [comment]
Here's a tabulation of food restrictions and allergies that we should be aware of when ordering food for catering. We should strive to accommodate the most common restrictions, and inform participants when we cannot accommodate their dietary restrictions due to logistical constraints. 

**N.B.** Some participants checked multiple options, so there is some overlap between the rows of each table. 

## Dietary Restrictions

| Dietary Restrictions | Number of Participants |
| :-- | --: |
| Vegetarian | 13 |
| Halal | 8 |
| Pescatarian | 7 |
| Vegan | 4 |
| Kosher | 3 |
| Paleo diet | 1 |

## Allergies

| Allergies | Number of Participants |
| :-- | --: |
| Lactose intolerance | 4 |
| Shellfish | 2 |
| Peanuts | 1 |
| Tree nuts | 1 |

**Comment by adrisua** [comment]
@irobii @eringill @ananab Thanks for offering your help before the event. We are looking into food and rental options. Here is a list of a couple of things we need help with so feel free to write your name on an item. Let me know if you have questions or ideas!

## Tasks

| Task description | Person in charge | Deadline |
| --- | --- | --- |
| Get quotes for the rental of 6 black table throws |  | Oct 4 |
| Determine the amount of pizza needed from panago and uncle fatih's pizza for 120 people including the dietary restrictions above. Both of these places may offer deals for us | @ananab | Oct 4 |

**Comment by irobii** [comment]
@adrisua I'm interested in "Determine the amount of pizza".
When should I do the task before the event? (Please let me know date and time.)

**Comment by BrunoGrandePhD** [comment]
I've tidied up the [**logistics spreadsheet**](https://docs.google.com/spreadsheets/d/1od5J4I_Rbtqx-A4PEJOmDW7EZfqPXumYGg2iiibSv1U/edit#gid=501875787) by consolidating everything into one sheet. I find it makes it easier to have a global view of what needs to be done. By the way, I've merely hidden the previous sheets; you can still see them in View > Hidden Sheets. 

@adrisua: Do you want to meet sometime soon for a "logisticathon"? Basically, I'm envisaging 1-2 hours dedicated to figuring out as many things as possible. Being co-located would allow us to readily bounce ideas off of each other. It probably makes more sense to do it during a weekday, so we can call the companies. I would be available for 1-2 hours tomorrow morning or Friday afternoon. If you don't think meeting in person is necessary, that's fine by me.

**Comment by adrisua** [comment]
@irobii Awesome. The sooner the better. Would you be able to have that information for this Friday (October 30th before midnight) ?

**Comment by irobii** [comment]
@adrisua Ooops! I'm sorry. I should cancel the task for "Determine the amount of pizza". I'm currently outside of Canada and I'll arrive at UBC one day earlier before the event.

**Comment by ananab** [comment]
@adrisua in the case of @irobii changing her plans, I can help with determining the amount of pizza needed

**Comment by adrisua** [comment]
That would be fantastic @ananab! Let me know if you have questions. The idea is to have amounts for both places (panago and uncle fatih's) considering all the dietary restrictions. Thanks!

**Comment by ananab** [comment]
Hi @adrisua, I actually do have some questions. I saw the dietary restrictions and allergies above, where can I find information such as number of participants and budgets, discount provided, etc? Thanks a lot

**Comment by adrisua** [comment]
The total number of participants is 120 and the table above only includes those that have dietary restrictions. Our budget for lunch for one day is around $1 to $1.5k but we are hoping to pay less than that. To get a discount, panago asked me for the amount of food items we need first. We still need to ask uncle fatih's about a potential sponsorship.

**Comment by ananab** [comment]
Thank you @adrisua, I'll be working on this. I am quite occupied today and tomorrow but I should be able to get back to you next week

**Comment by BrunoGrandePhD** [comment]
Response from UBC IT:

> Hi Bruno,
> 
> I've talked to our wireless group and they believe the existing wireless coverage in Life Science Centre is sufficient to provide service to your group so no temporary access points will be required. The cost for a custom SSID is $250.
> 
> I would like to point out that since your event is happening over a weekend we do not have weekend or after hours support for wireless issues. Other groups who have held similar events have chosen to have a network switch backup plan in case there are issues with the wireless. In that case they rent a network switch that we come in and configure for you to plug directly into if required. None of the other groups have ever had to use this backup but preferred having something just in case. The rough estimate for that back up would be about $500 depending on how many switches you would require.
> 
> The other option would be to pay to have someone on call from the wireless team but I believe that would end up being more expensive.
> 
> Let me know if you are concerned about having backup or not and if you want to move ahead with the SSID. I will need an SSID name from you and password to set up for your users.
> 
> Thank you,
> Sarah

@adrisua: Do we go with the backup plan (~$500) in addition to the custom SSID ($250)?

**Comment by adrisua** [comment]
@ananab For halal, pescatarian, kosher and paleo we can get vegetarian options.

**Comment by BrunoGrandePhD** [comment]
My response to UBC IT:

> Hello Sarah, 
> 
> We are sure to go with the custom SSID for authentication. The SSID name and password would be "hackseq" and "genomics", respectively. Can you confirm that this new SSID will be available in the LSI East Atrium and LSI rooms 1330, 1410 and 1416? Thanks. 
> 
> I believe the LSI East Atrium tables have Ethernet ports. Do you know if they are operational? If so, we wouldn't need network switches if ever the wireless network goes down. We would need a number of Ethernet cables on hand though. Does UBC IT have spare cables they could lend us for the weekend?

**Comment by BrunoGrandePhD** [comment]
## Team Placement in UBC LSI

I've been thinking about how teams will be laid out on the long tables in the East Atrium. By default, the tables have 16 chairs (see [image](http://www.vancitybuzz.com/wp-content/uploads/2015/09/UBC-Life-Sciences-Institute.jpg)). However, I think we can fit 4 more spots on each table, if necessary: one on each end and one in the middle on each side. This would give a max capacity of 20 spots for each long table.

Here are the number of members per team according to GitHub:

| Team | Members |
| --- | --- |
| Team 2 | 7 |
| Team 4 | 11 |
| Team 5 | 8 |
| Team 6 | 10 |
| Team 7 | 9 |
| Team 8 | 11 |
| Team 9 | 9 |
| Team 10 | 10 |
| GA4GH | 20? |

If we pair teams with 11 members with teams with 7-8 members, then we can fit two teams per table. Team leaders can sit at the end with a nice view on their entire teams. One table would be left for the GA4GH teams (assuming they bring 20 people or less). The final table could be used for registration, swag, food and drinks (I'm thinking of it being in the middle). We could rent smaller tables for the sponsors.

**Comment by BrunoGrandePhD** [comment]
Response from UBC IT: 

> Hi Bruno,
> 
> There are existing outlets in the atrium so we can activate them for you but that would require a custom VLAN creation which is $250. That would but your total to about $500 for the event. If you would like to do that please let me know and I will also need to know which ports you want activated at the location. Will you be at the location before the event dates? If you are then I just need the CCT number off the ports you would want activated for back up purposes.
> 
> The SSID will be available throughout the Life Science building, not just in those locations. I'll move ahead with getting that set up for you.

We can discuss this at the meeting this evening.

**Comment by GalenWright** [comment]
@brunogrande one of the participants wrote: 

> I can bring an ethernet cable but I said "no" because my macbook does not have ethernet port. Please let me know if you think I should bring a cable. 

Something to consider with the mac users - I guess some would have adapters though

**Comment by ananab** [comment]
@adrisua here is a plan for pizza before discount.
[hackseq_pizza.pdf](https://github.com/hackseq/October_2016/files/507380/hackseq_pizza.pdf)

**Comment by adrisua** [comment]
That is amazing, thanks so much @ananab! Would you like to arrange the order with panago and uncle fatih's? If yes, let me know and I will provide more info.

**Comment by ananab** [comment]
@adrisua sure, I don't see why not. If the plan works with you I can arrange the ordering.

**Comment by adrisua** [comment]
Awesome :) The phone number from panago is 604-671-8584. Please, let them know that you are calling on behalf of Adriana Suarez from hackseq. We applied for sponsorship but they offered a discount instead. The lunch is for Sunday October 17 at 11:30 am (hopefully both order will arrive before noon) and the address is 2350 Health Sciences Mall. Thanks so much again!

**Comment by ananab** [comment]
@adrisua thank you for the information. So do we order from both places or just Panago? the current plan is to order half of the pizza from each place. If we just want Panago we can double its order (but the price may go up a bit since it's more expensive, before discount at least), or we can reduce the total amount if you want to keep the budget unchanged. Please let me know.

**Comment by adrisua** [comment]
@ananab Would you mind asking in panago how much the full order (including the discount + delivery) would be? If the total is more than $800, let's go with uncle fatih's. Thanks!

**Comment by ananab** [comment]
@adrisua sure, I will do that tomorrow. Just to make sure, you are happy with the amount of ordering, that is, 44 pizzas in total. Also, do you have a contact number for Uncle Fatih's pizza as well or should I just call the nearest location?

**Comment by ananab** [comment]
hey @adrisua, panago is willing to give a 20% discount and the price is $709.96 after tax. It would be great if you can give me a contact number for delivery so I can make the order

**Comment by adrisua** [comment]
Let's go with Panago then. To double check the quantity, you could ask in panago if that order will feed ~120 people. As for a contact phone number, please use: 604-657-0973. Thanks soooo much!

**Comment by adrisua** [comment]
@ananab Thanks so much! I just confirmed with Panago the order.

**Comment by ananab** [comment]
@adrisua awesome. Glad I could help. See you at the event then

**Comment by BrunoGrandePhD** [comment]
Responded to UBC IT:

> Hello Sarah, 
> 
> We are going to proceed with the activation of the Ethernet ports in the LSI East Atrium on the long tables. I've included below the list of CCT numbers to be activated. I'm assuming they're inactive; I wasn't able to confirm this, as I didn't have a cable with me when I visited the venue. Is the creation of a custom VLAN required if the ports are already active? If not, then I might want to check first if they are active or not (or you can check on your end). 
> 
> [Number are attached instead: [cct_numbers.txt](https://github.com/hackseq/October_2016/files/518042/cct_numbers.txt)]

**Comment by BrunoGrandePhD** [comment]
UBC IT responded by informing us that there is actually a limit of 12 ports for the $250 and that each additional batch of 12 is an extra $100. 

> Hi Bruno,
> 
> I didn't expect you would need that many, for the price I gave you we can give you 12 activated ports. Any additional 12 that you need would be an additional $100 as it would require a larger VLAN capacity.
> 
> About 6 of those ports are not connected because they were not used and so were re-purposed to other areas of the building. The rest are ready to be used once assigned to a VLAN for you. The current VLAN they are assigned to would require the user to log in using CWL which you're users won't have.
> 
> Let me know how many ports you would want activated based on the cost of $250 for the first 12 and $100 for each group of 12 after that. Also let me know which ports from this list you would choose, I have removed the 6 that are not available. I will need to know this ASAP so I can place the request for the VLAN to be created by Friday.
> 
> [I've omitted the list of available CCT numbers for brevity.]

I responded by asking if they can offer us a compromise, since we don't have much time to re-visit the venue and strategically select ports. 

> Hello Sarah, 
> 
> The primary reason we are activating these ports is to have a back-up plan in case the wireless network goes down during the weekend, since UBC IT will not be able to provide support. Obviously, we cannot afford to have an IT specialist on call, because we are completely self-funded and have several other costs to cover. 
> 
> Would it be at all possible to reach a compromise and activate all available CCT numbers for $250? Had we been informed of the 12-port limit, we would have been more strategic in noting which CCT numbers to activate when we visited the venue last week. And it sounds like we don't have time to re-visit the venue in order to activate the ports by Friday. 
> 
> Let us know if there is anything you can do to accommodate our tricky situation. We greatly appreciate any help you can provide!

**Comment by santina** [comment]
Hey, I'm going to UBC today and will be measuring the table length. Since I'll be revisiting the venue, let me know what the IT says. If they respond negative, I can take a look at the port numbers.

**Comment by BrunoGrandePhD** [comment]
Amy will be picking up the table throws tomorrow morning.

**Comment by BrunoGrandePhD** [comment]
The rest of the conversation with UBC IT:

Their response:

> Hi Bruno,
> 
> Unfortunately I am not able to get a VLAN created for the size you want (activating all ports) for that cost. I need to get the request in now if I want a chance at activating any of the ports. I will activate 24 ports and will send you a list of those ports that are activated for a cost of $250. Then if you end up needing them (hopefully you will not) then you would need to look for the ports I have activated.

My response (the CCT numbers were chosen to be spread out across the tables): 

> Hello Sarah, 
> 
> I appreciate the offer of activating 24 ports for $250. I think we can make do with that if worst comes to worst. Actually, I have selected 24 ports that I would prefer to be activated. They should be evenly spread out across the tables we are going to use. Let me know if you will go with this list. Thanks!
> 
> CCT039156
> CCT039158
> CCT039160
> CCT039162
> CCT039164
> CCT039166
> CCT039172
> CCT039174
> CCT039176
> CCT039178
> CCT039180
> CCT039182
> CCT039187
> CCT039371
> CCT039375
> CCT039379
> CCT039381
> CCT039383
> CCT039385
> CCT039390
> CCT039392
> CCT039394
> CCT039397
> CCT039399

Their response:

> Hi Bruno,
> 
> We have created a new VLAN for the ports listed in your last email, they have all been activated for you now. The VLAN information is:
> 
> VLAN ID: 1836
> VLAN Name: DNET-HACKATHON
> IP Subnet: 209.87.17.128
> Subnet Mask: 255.255.255.224
> Gateway: 209.87.17.158
> DHCP Enabled: Y
> DHCP Servers: 137.82.1.2 142.103.1.42
> Usable IP Range: 209.87.17.129 - 209.87.17.157
> 
> Your SSID will be set up tonight and ready for you tomorrow morning. Please test it tomorrow when you are setting up and if you run into any issues let me know right away so we can address it before the weekend.
> 
> If you have any questions please let me know.

My response: 

> Hello Sarah, 
> 
> I appreciate the quick turnaround time on getting the VLAN activated. Just to be clear, does anything needs to be done on the user's end to connect to the Internet other than physically connecting to the port?

**Comment by santina** [comment]
How are we supposed to test it and let them know before the weekend if we can only test it tomorrow?

**Comment by ababaian** [comment]
What time should we arrive tomorrow AM to help set-up?

**Comment by santina** [comment]
Let's discuss on slack. I say 7:30.

**Comment by BrunoGrandePhD** [comment]
One thing left to do with this ticket is settle with UBC IT. I'll tell them that the ports weren't working and that we hope that we do not have to pay for the $250 for the VLAN activation.

**Comment by BrunoGrandePhD** [comment]
UBC IT figured out a problem with the VLAN setup (for Ethernet ports, which didn't work during Hackseq) on their end. We will thus only pay for the custom SSID network, which costs $262.50. We can either pay with a cheque addressed to UBC or in person at the Klinck Building (cash or debit). 

@adrisua, what do you think is the best way to pay?

**Comment by adrisua** [comment]
Could we get an invoice addressed to SCWIST including hackseq?
