### ISSUE TITLE
Final hackseq steering committee planning meeting

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#55]
We need to plan the next and final hackseq steering committee planning meeting! We will hold it at the LSI in the atrium so that we can see that space we will be in at the event. Please fill out this survey so we can figure out the best possible time for all: http://whenisgood.net/jxrnhjk

To see survey results, use the following results code: r43nh5r

**Comment by ttimbers** [comment]
@hackseq/steering_committee, please fill out this survey: http://whenisgood.net/jxrnhjk

**Comment by BrunoGrandePhD** [comment]
@minisciencegirl @cloucks: Would you be able to make it to a meeting on Monday evening?

**Comment by minisciencegirl** [comment]
Yes. Let me know the time.

**Comment by ttimbers** [comment]
@hackseq/steering_committee - the best time for everyone looks like 5pm tomorrow (Monday, Oct 3). We will meet in the LSI. Let's meet near the Cafe Perugia entrance. I'll make sure to be there early before the doors lock so I can let everyone in.

**Comment by sjackman** [comment]
I'll see you tonight, but I'll have to leave early to get home to watch the kids.

**Comment by ttimbers** [comment]
Hiya folks - I've been sick since Thursday and I'm still not well today and so think I need to go home soon. Meaning I won't be able to attend the meeting :(

Can someone else be there by 4:30pm (that's when the doors lock) so that they can let others in? Sorry to do this at the last minute, but I really hoped to be feeling better by today :(

**Comment by sjackman** [comment]
Sorry to hear that you're not feeling well, Tiffany. 🤒 Rest up.

I won't be able to be there by 4:30.
@hackseq/steering_committee Is anyone on UBC campus?

**Comment by adrisua** [comment]
I'll be there before 4:30 pm. Get good rest and I hope you feel better soon Tiffany.

**Comment by cloucks** [comment]
I'm sorry I won't be able to make it tonight, or to the week of the event, since my due date is almost here. It was really nice working with everyone!
