### ISSUE TITLE
Hackseq Steering Committee member schedule during hackseq

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#56]
@hackseq/steering_committee - please fill out your availability during hackseq (i.e., when do you promise to be there to help out):
### Steering Committee Member availability during hackseq

| hackseq Steering Committee Member | Sat AM | Sat PM | Sun AM | Sun PM | Mon AM | Mon PM |
| --- | --- | --- | --- | --- | --- | --- |
| Artem Babaian | Y | Y | Y | Y | N | Y |
| Britt Drogemoller | Y | Y | N | N | Y | Y |
| Bruno Grande<br>(**N.B.** I'm participating on a team.) | Y | Y | Y | Y | Y | Y |
| Shaun Jackman | Y | Y | Y | Y | Y | Y |
| Amy Lee | Y | Y | Y | Y | N | N |
| Santina Lin | Y | Y | Y | Y | Y | Y |
| Catrina Loucks |  |  |  |  |  |  |
| Adriana Suarez-G | Y | Y | Y | Y | N | Y |
| Tiffany Timbers | Y | Y | Y | N | N | Y |
| Galen Wright | Y | Y | N | N | Y | Y |

**Comment by santina** [comment]
If GA4GH is doing a one-day hackathon on the last day, then I'd be very interested in doing that. I'm also interested in attending some talks, but it depends on how much work we have.

**Comment by sjackman** [comment]
I'm leading a project so will be limited in how much I can help out during the main 9 to 5 times.

**Comment by ttimbers** [comment]
FYI - I had to switch my availability on Sunday, I am now only available in the AM. Apologies!
