### ISSUE TITLE
Brainstorm questions/ideas for voting form for people's choice award

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#57]
- Have participants rank top 5 projects for best overall (People's choice award)
- We award 1st place and a runner-up based off these rankings

**Comment by adrisua** [comment]
@ttimbers so we are thinking about a 5-10 min presentation per team, correct? We are having a big prize of $3k and will cover publication fees (up to $200) to the teams that submit a manuscript before a deadline (two weeks or a month after hackseq). We could ask them to include their plans to publish in their presentation.

**Comment by ttimbers** [comment]
@adrisua - OK, prize goes only to first place, but I think runner up for votes should get an honorable mention at the event (and on our website & Twitter!). 

Maybe we only need people to pick their top 3 projects then, and the you get the inverse points for your ranking, being ranked # 1 by someone gets you 3 points, # 2 gets you 2 points, and # 3 ranking gets you 1 point. We add up the points and that's how we choose the winner.

Is  (two weeks or a month after hackseq) long enough to write up and publish something? Definitely not in my field... Why such a short deadline. Could we do 4-6 months instead?

**Comment by ttimbers** [comment]
Oh, and let's keep the presentations to 5 minutes. People invariably always go over the given time, and 5 \* 10 is already 50 minutes! I think that will be the max attention span at the end of the event.
