### ISSUE TITLE
Saturday night social

### ISSUE THREAD

**Issue by ttimbers** [hackseq/October_2016#58]
I cannot determine from the budget (nor remember from our discussions) if we have a budget for the Saturday night social? I think I remember we said Saturday night was going to be informal? Everyone buys there own kind of thing? Please correct me if I am wrong.

**Comment by adrisua** [comment]
That is correct. Although we don't have a budget for the social on Saturday and it will be informal, we might need to book a space. @minisciencegirl would it be possible to talk with Joe about this? We could go to the Pit on Sat and to the Gallery on Monday.

**Comment by ttimbers** [comment]
I've also emailed Mahoney's to ask how busy they usually are on a Saturday, and what their capacity is.

**Comment by minisciencegirl** [comment]
Sounds good @adrisua. I will go ahead and provide an estimate of 50 - 100 people for Saturday.

**Comment by minisciencegirl** [comment]
@adrisua: October 17th at the Gallery is confirmed. Unfortunately the Pit is reserved for October 15th for a private function. Gallery is still open - do we want to do two nights at the Gallery?

**Comment by adrisua** [comment]
Sure, let's do that.

**Comment by minisciencegirl** [comment]
Saturday night Social will happen at the Pit. They have a private function but they don't mind us using the other portion of the pub. Everything is confirmed.
