### ISSUE TITLE
Drafting email for participants

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#59]
Things to bring
- utensils, mugs, etc
- Computer, power cord, ethernet cable, etc

Things to install
- Basic things like Slack, Git, Python, etc
- Check with your team leader

Info
- Travel, lodging

**Comment by Brittdrog** [comment]
I have put together a draft for [email ](https://docs.google.com/document/d/1qqm8rDBkIP7P7NjZvFAx5TJvNXd9itnyNlF9bJHMSeI/edit?usp=sharing)to send to the participants and team leaders. 

I plan to send it out on Saturday (1 week before _hackseq_), so let me know if there is anything that I have missed before then.

**Comment by santina** [comment]
Need to mention 
- downloading slack on the phone since that's the main mean of communication
- workshops (esp since the Git workshop requires some preparation)
  Do they need to buy any ticket for the social? 
- Including sponsors in the email

**Comment by Brittdrog** [comment]
Thanks @santina - I see you have made the changes:-) 
I don't think we are selling tickets for the socials anymore. @adrisua @minisciencegirl - is this correct?

**Comment by minisciencegirl** [comment]
We are not selling tickets for the social. But here is the event detail:

1) October 15, Saturday, 6pm - Join us for a fun evening to meet fellow hackseq participants at the Pit Pub!

2) October 17, Monday, 5pm - Amazon AWS sponsored community/ hackseq event at the Gallery! Come meet the Vancouver hacking/ tech/ genomics community!

**Comment by Brittdrog** [comment]
Thanks @minisciencegirl - I have made these changes. I just took out "Vancouver" because there are so many participants from all over the world that will be attending.

If no-one else has any suggestions, I will send out the email tomorrow.

**Comment by minisciencegirl** [comment]
@Brittdrog: Thank you!

@santina: Here is the eventbrite url for Monday's event if you would like to include this in your email to participants!
https://www.eventbrite.ca/e/hackseq-2016-social-tickets-28463797986

**Comment by santina** [comment]
I see @Brittdrog included it. Thanks! I think it looks good. If there's no other comment from the rest of the team, we can send it off tomorrow.

**Comment by Brittdrog** [comment]
@brunogrande - do you have a list of the emails for everyone who is attending hackseq? If you do, could you send out the [email](https://docs.google.com/document/d/1qqm8rDBkIP7P7NjZvFAx5TJvNXd9itnyNlF9bJHMSeI/edit) to this list?

**Comment by BrunoGrandePhD** [comment]
@Brittdrog: I'm working on this.

**Comment by BrunoGrandePhD** [comment]
@Brittdrog: You refer to an "attached map". What did you have in mind?

**Comment by Brittdrog** [comment]
@brunogrande - no worries....if you don't have a list already, I can do it. 
I have a map that I made showing where the entrance is. 
I will send out the email tomorrow

**Comment by BrunoGrandePhD** [comment]
I already compiled a [list of emails](https://github.com/hackseq/October_2016_private/issues/24#issuecomment-252459200). The email draft exists in the Hackseq Gmail account, and it already addresses all participants and team leaders. You can simply add the map and send it off! 😊

**Comment by Brittdrog** [comment]
@brunogrande - awesome! That was super efficient. I have attached the map, but am going to wait until tomorrow to send it out (as Saturday night is probably not the best time to receive emails).

**Comment by Brittdrog** [comment]
Sent.
