### ISSUE TITLE
AWS cloud credits

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#6]
@sjackman I started the application for the [AWS cloud credits](https://aws.amazon.com/research-credits/)
The deadline is **June 30**, by then we might have a better idea of what we need.
Here are 3 key things we need to apply (Would you mind helping with this section? We can chat more about it during our meeting in May and I will send you a friendly reminder in mid-April. If you are too busy we could ask someone else to help us): 
1. “Please use the [simple monthly calculator](http://calculator.s3.amazonaws.com/index.html) to estimate your monthly AWS bill based on various AWS services to be used, then multiply by the expected duration of your project. If your project involves interruption-tolerant jobs, we strongly encourage you to plan for the use of Spot Instances and alter your budget accordingly. Please see our [FAQ](https://aws.amazon.com/research-credits/faq/) for more information”
   “Save and Share URL from Simple Calculator*”
2. Proposed AWS solution (including specific AWS tools, timeline, key milestones).
3. AWS Credits Desired for Entire Project in USD (one year maximum)\*  

Another item we might need to discuss is this section:
- Any potential future use of AWS beyond grant duration by individual research group or broader community.

Thanks!

**Comment by adrisua** [comment]
@sjackman I got in touch with Gaurab Basu from AWS in Seatle and he is willing to answer questions we might have about the application. Just let me know.

**Comment by sjackman** [comment]
See https://aws.amazon.com/ec2/pricing/

My upper bound estimate for the weekend is $7000 USD. It's likely much less than that.
That estimate is based on one 64 GB machine per person \* 100 people \* 72 hours. One 64 GB machine is 96 cents per hour.

$0.958 \* 100 \* 72 = 6897.60

In the project proposal we should ask the team leaders whether they need any HPC at all. If they do, ask for a rough estimate of the amount of RAM required for their analysis. An 8 GB machine is only $0.10 per hour, a tenth of the cost of a 64 GB machine, but many people's laptops have that much RAM, in which case we wouldn't need to rent a machine at all. If the machines are only needed during the day (8 hours per day rather than 24), then the cost will be a third.

**Comment by sjackman** [comment]
Data storage costs will be minimal for a few days. I'll have to look into whether data transfer costs are a consideration. If anyone is planning on transferring multiple large sequencing datasets, it may be a consideration.

**Comment by sjackman** [comment]
I'm thinking that it makes more sense that each team would share one machine (or possibly more) of sufficient size to suit that project's purposes, rather than one machine per participant. Let's ask the team leaders the following questions:
- Will your analysis use any AWS Public Data Sets?
- What is the size of your data in GB?
- How many of the following AWS EC2 machines does your project require, for the team to share?
  - No HPC needed. The participants' laptops are enough.
  - m4.large with 8 GB RAM
  - m4.xlarge with 16 GB RAM
  - m4.2xlarge with 32 GB RAM
  - m4.4xlarge with 64 GB RAM
  - m4.10xlarge with 160 GB of RAM
  - Other?
- How large a hard drive does each machine require in GB?

**Comment by sjackman** [comment]
The application looks pretty straight forward.
https://aws.amazon.com/research-credits/
1. Brief description of problem to be solved.  
   Describe the HackSeq workshop in general terms. Include a one-sentence summary of each project.
2. Proposed AWS solution (including specific AWS tools, timeline, key milestones).  
   AWS EC2, EBS and S3. Oct 15–17.
3. Plan for sharing outcomes (tools, data, and/or resources) created during project.  
   We should require that each project post a summary of their results to be posted on the HackSeq web site. We should also distribute any data resulting from their analyses?
4. Any potential future use of AWS beyond grant duration by individual research group or broader community.  
   Many participants will likely not have used AWS before, and this workshop will serve as their introduction to cloud computing and Amazon Web Services.
5. Names of any AWS employees you have been in contact with.  
   Gaurab Basu from AWS in Seattle
6. Any AWS Public Data Sets to be used in your research.  
   We'll have to ask the team leaders this question.

**Comment by sjackman** [comment]
1. Brief description of problem to be solved.

Describe the HackSeq workshop in general terms. Include a one-sentence summary of each project.

2. Proposed AWS solution (including specific AWS tools, timeline, key milestones).

AWS EC2 and S3. Oct 15–17.

3. Plan for sharing outcomes (tools, data, and/or resources) created during project.

We should require that each project post a summary of their results to be posted on the HackSeq web site. We should also distribute any data resulting from their analyses?

4. Any potential future use of AWS beyond grant duration by individual research group or broader community.

Many participants will likely not have used AWS before, and this workshop will serve as their introduction to cloud computing and Amazon Web Services.

5. Names of any AWS employees you have been in contact with.

Gaurab Basu from AWS in Seattle

6. Any AWS Public Data Sets to be used in your research.

We'll have to ask the team leaders this question.

**Comment by sjackman** [comment]
Estimating 20 teams and one m4.4xlarge machine with 64 GB of RAM and 500 GB of storage per team, and some wild, hopefully on the high side, guesses about data transfer requirements, the cost estimate is $3576.93 USD. Here's the AWS cost calculator:
http://calculator.s3.amazonaws.com/index.html#r=PDX&s=EC2&key=calc-7C5A8FDE-8340-4C8E-B8F1-66D57C4B00BB

**Comment by sjackman** [comment]
> What is the size of your data in GB?

I'm going to estimate that the size of the data transferred in (which is free) is going to be the same size as the data transferred out (which costs money).

**Comment by DCGenomics** [comment]
We have run several of these things through AWS, and cost for 5 teams has
run ~~$1500 for a three day event.

I can put you and Adriana in touch with some folks I know at Amazon and/or
other cloud providers at some point.

Cheers!
Ben

**Comment by sjackman** [comment]
That's very helpful. Thanks for the estimate, @DCGenomics. (Do you have a real first name, that I can call you?)
My estimate of $179 per team seems to be on the low side then. Do you have a breakdown of the costs at $300 per team? I'd like to know if I was underestimating the cost of storage and transfer.
@adrisua has a contact, Gaurab Basu from AWS in Seattle.

**Comment by DCGenomics** [comment]
Sure, my name is Ben Busby, and I work at NCBI.

Im also looping Matt Lesko from NCBI, who has been the technical lead for
our hackathons in on this conversation.  He can give you a specific
breakdown of costs per team (as you suspected before, its not the same for
each team).

Cheers!
Ben

**Comment by nyetsche** [comment]
For such a short period of time (72 hacking hours, plus a few more to set things up and tear them down), the cost of an instance dominates. We've been pretty successful with giving each team a `m4.4xlarge` on Day 1 and one large root volume (~2TB, or more if somebody knows ahead of time). That's `$0.958/hr/team` as you identified earlier.

The advantage of AWS is that one can spin up more and larger instances as needed. We had one team working with [RNASeq](https://github.com/NCBI-Hackathons/RNA-seq_Comparison_Pipeline) that requested, and used 100%, two additional `m4.10xlarge` instances.

So the answer is ... it depends. $300/team is sort of a "high-but-low" bound: it's conceivable that's not enough for the more computationally demanding users. And it's notoriously hard to estimate resource requirements. But it's sufficient for "most" teams.

**Comment by minisciencegirl** [comment]
@sjackman: is there any plan to use Galaxy at the hackathon?

**Comment by sjackman** [comment]
No plan, and I have little experience with Galaxy myself, but let's get feedback from the project leaders if that would be useful to them.

**Comment by BrunoGrandePhD** [comment]
My supervisor was considering leading a team focused on Galaxy tool development. However, we would just install Galaxy on vanilla EC2 instances.

**Comment by minisciencegirl** [comment]
That's fantastic @brunogrande! I will let the Galaxy Project people know - they mentioned that they will heavily promote the event if it's linked to Galaxy.

**Comment by sjackman** [comment]
Great!

**Comment by GalenWright** [comment]
I received an email from Angel Pizarro from Amazon on the hackseq gmail

> Hello hack seq team. Would it be helpful to provide AWS credits to the participants? If so let me know and I can start the process. 

@sjackman could you possibly correspond with them via our gmail? It could be a good opportunity. Thanks!

**Comment by sjackman** [comment]
I'd prefer to use my own e-mail address and cc the Hackseq e-mail address. Does that work for you? Yes, I'd be happy to follow up. Is this so that the participants can have some AWS credits in their name, not belonging to Hackseq? That does seem useful so they can do some follow up work after they leave.

**Comment by GalenWright** [comment]
Thanks, that works for me. I will forward the email to the gmail you have listed on your GiHub profile. I'm not sure, but I that seems what they are proposing.

**Comment by sjackman** [comment]
Summarizing the project proposals

5 projects require HPC
1 project will use an AWS data set
The data size totals 2 TB: `1, 1000, 2, 700, 100` (GB)
The hard drive sizes total 17 TB: `2*100 + 7*2000 + 6*32 + 1000 + 1000` (GB)
The requested machines: 1 large, 6 xlarge, 13 10xlarge

I'll put together a new AWS cost estimate spreadsheet for these resources. I don't have a good idea really of what I/O usage will be.

**Comment by sjackman** [comment]
@gracezheng Which public AWS data sets will you be using?

**Comment by gracezheng** [comment]
We have not released the dataset to the public yet. But it'll be similar in nature to this one, except the matrix file is about 0.5GB.

**Comment by sjackman** [comment]
Will you be using a public data set this already available on AWS? https://aws.amazon.com/public-data-sets/

**Comment by sjackman** [comment]
[Updated cost calculator estimate](http://calculator.s3.amazonaws.com/index.html#r=PDX&s=EC2&key=calc-98B78ADC-E35B-45D2-B120-B953469DF96C)
10 m4.4xlarge and 13 m4.10xlarge with 16 1 TB hard drives and 7 2 TB hard drives

**Comment by sjackman** [comment]
I have submitted the AWS credits application:

> We are organizing the Hackseq Genomics Hackathon http://www.hackseq.com in the three days prior to the The American Society of Human Genetics (ASHG) 2016 meeting Oct 15-17 in Vancouver, Canada. We have 9 teams participating, each team with an estimated 5-10 participants, for a total estimated 50-100 participants.
> 
> The project leaders have provided estimates of the compute requirements for each of their projects. The total compute requirements of all the projects is 10 m4.4xlarge and 13 m4.10xlarge most with a 1 TB hard drive, and 7 with a 2 TB hard drive.
> 
> The teams will collaborate using GitHub. The results of each analysis will be shared using GitHub Pages. We will summarize these results on the Hackseq web site and share them on social media, primarily Twitter.
> 
> Many participants will not have used AWS before, and this workshop will introduce those participants to AWS. The participants may choose to continue to use AWS after the workshop has completed.
> 
> We have communicated with Gaurab Basu from AWS in Seattle, and Angel Pizarro.
> 
> I have provided my personal AWS Account Number. Should we set up a new AWS Account for this workshop?
> 
> Thank you for your support. My best regards,
> Shaun Jackman
> http://sjackman.ca
> http://www.hackseq.com

**Comment by sjackman** [comment]
We have been awarded $7500 (30 codes of $250 each)!

**Comment by minisciencegirl** [comment]
Well done @sjackman!! Go Team!!

**Comment by BrunoGrandePhD** [comment]
@sjackman: Are team leaders aware that they will be able to use AWS during Hackseq? If not, I can include this in an email to team leaders describing what they can do prior to Hackseq (related to hackseq/October_2016_private#29).

**Comment by sjackman** [comment]
Good catch. We haven't yet told the team leaders about AWS. The team leaders definitely need to create an AWS account in advance of Hackseq, as they require authentication by a text / phone call and take a few days to approve. About half of the team leaders said they didn't need any HPC services. I would encourage them to create an AWS account just in case. We're also going to create BCGSC ORCA Docker accounts (a new BCGSC container HPC service) for all the participants. Please tell them to expect an e-mail with instructions to create those ORCA accounts.
http://www.bcgsc.ca/services/orca/

**Comment by DCGenomics** [comment]
Have aws account

**Comment by Brittdrog** [comment]
@sjackman Melissa (one of the team leaders) asked the following about the AWS credits

> Was there a default amount requested for each team? I'm sorry if I missed that. 

Are the codes available based on what the team leaders requested in their original applications? Or are there codes available for everyone? Is there any other information that the team leaders need to know that I should add to the final email to them?

**Comment by sjackman** [comment]
Each team was allocated the amount that they requested. If they did not request any, they were allocated $250.

> Distribution of 30 codes: 
> Teams 10, 4, 2 should be given 4 codes per EACH team ($1,000 per team).
> Team 8 gets 8 codes ($2,000)
> Team 7 gets 5 codes ($1,250)
> Teams 9, 6, 5, 1 get one code EACH ($250 per team)
> There will be one remaining code of $250 for additional needs.

There was some confusion with the GitHub project issue numbers, before they were renumbered for the form. I'll have to double check my notes at work to make sure that these project numbers are correct.

**Comment by Brittdrog** [comment]
@sjackman - that is awesome! Melissa did not request anything, but I will reply and let her know that each team has been assigned one code. Thanks!

**Comment by Brittdrog** [comment]
Melissa has some more questions regarding the AWS codes:

> What is one code worth in terms of compute hours?
> 
> Should we just have one person on AWS?

@sjackman @brunogrande can you answer these questions? Do you think it may be good to include how this will work in the intro session?

**Comment by sjackman** [comment]
Each code is worth $250. The price per hour depends on the size of the machine. An `m4.4xlarge` machine with 16 cores and 64 GB of RAM is roughly $1 / hour. The pricing schedule is here: https://aws.amazon.com/ec2/pricing/on-demand/
The project leader will start up the machine(s) and then any number of participants can log into that machine. You pay per machine (not per user logged in).
Yes, let's give a short introduction to AWS at the opening session.

**Comment by Brittdrog** [comment]
@sjackman - perfect. Thank you!

**Comment by gracezheng** [comment]
Where can I get the codes for team 7? I'd like to upload some files on amazon for my team members to download.

Thanks

**Comment by sjackman** [comment]
Hi, Grace. I've sent you your first AWS code on Slack.
