### ISSUE TITLE
Look into hackseq shirts

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#61]

**Comment by santina** [comment]
or figure out something identifiable that volunteers and organizers can wear

**Comment by adrisua** [comment]
I liked the idea of wearing funny hats :) 
A cheap alternative is wearing black t-shirts with some hackseq stickers on it

**Comment by santina** [comment]
Will check dollar store for Halloween wears ;😈

**Comment by BrunoGrandePhD** [comment]
So, what did we decide for this?

**Comment by ababaian** [comment]
Just saw this.

For the name tags, there are different labels on jobs each person has. Most importantly all the participants wll write their name in black marker on the name tags and the organizers/volunteers will use red. It will be a quick way to distinguish people.

**Comment by santina** [comment]
Went to the dollar store, found no good Halloween wears unless we wear cheap plastic wings or uncomfortable hair wear. 
So let's just all wear a black shirt, and with the name tag that should be easy enough. 

Plus we'll all be sitting at the middle table, which will make it easy for people to find us.
