### ISSUE TITLE
Draft presentation for the opening

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#62]
For Saturday morning, content need to include (not limited to):

**Comment by adrisua** [comment]
## Opening

LSI Atrium, Oct 15th, 9 am

### Tentative plan (feel free to edit)

| Description | Person in charge |
| --- | --- |
| Introductions hackseq team; mission & vision | Adriana |
| Acknowledge sponsors | @brunogrande |
| Introductions: team leaders | @Brittdrog |
| Publications: f1000 | @sjackman |
| Agenda, PRIZE, info |  |

**Comment by adrisua** [comment]
We will have to do the welcoming in the atrium and project our voice the best we can.

**Comment by adrisua** [comment]
feel free to add you name or remove it

**Comment by DCGenomics** [comment]
Fwiw, I've always thought it was worth it to give each attendee 20-30
seconds to introduce themselves.

**Comment by sjackman** [comment]
I agree in principle, but 30s per attendee is 40 minutes. How about introductions informally over morning coffee and on Slack?

**Comment by DCGenomics** [comment]
Good call!

**Comment by Brittdrog** [comment]
@sjackman @DCGenomics @adrisua - I see I am down to introduce the team leaders - maybe we could just give the team leaders 20-30 seconds to introduce themselves? Otherwise I am happy to do it, but it might be a nice way for the team leaders to get involved?

**Comment by Brittdrog** [comment]
@adrisua - two other things we may need to include in the intro session
- Mention the travel award recipients (nice opportunity to highlight that we have people from all around the world)
- Give some info about the AWS codes

**Comment by adrisua** [comment]
The plan was doing that on Monday. This in when the representative from the ASHG will be there. We could also do it at lunch time on Sat if they are there.

**Comment by minisciencegirl** [comment]
@adrisua - regarding Social:

1) Saturday's event is limited only to 19 or older (BC legal drinking age) at the Pit

2) Monday's event is at Gallery 2.0, sign up to EventBrite and everyone is welcomed.
