### ISSUE TITLE
Do all the arts and craft for setup

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#63]

**Comment by santina** [comment]
We need someone to design the labels and @adrisua can print them 
1. Team labels: 
Make two labels per team: 
1.a. one that we could fold in a triangle and 
1.a. one that we could tape on the table. 
Each label should include the team # and a few logos from our sponsors. The idea is that all the sponsors are represented in these labels
1. Sponsor signs:
   Ideas.....
2. Other signs:
   Info?....

**Comment by adrisua** [comment]
@ababaian Would you like to design the team labels?

**Comment by adrisua** [comment]
@hackseq/steering_committee Who would like to help out with this? pretty please!

**Comment by santina** [comment]
Hey @adrisua  I can do that easily if we're just talking about a piece of paper with team number and logos of sponsors that we can tape on the side of the table. What do you mean by " one that we could fold in a triangle " ?

**Comment by adrisua** [comment]
Awesome. [This](https://www.google.ca/search?q=paper+in+triangle&safe=active&tbm=isch&imgil=9m23fc3zf9PyMM%253A%253Bo8e4z-j4xy813M%253Bhttp%25253A%25252F%25252Fwww.mindmapinspiration.com%25252Fhow-to-make-a-mind-map-triangle%25252F&source=iu&pf=m&fir=9m23fc3zf9PyMM%253A%252Co8e4z-j4xy813M%252C_&usg=__8C4XksBwmFjxzXsmCUlOwjaQS8Q%3D&biw=1280&bih=587&ved=0ahUKEwjmr7G96s7PAhUJ1mMKHZ5ZAmsQyjcIKw&ei=z8z6V6aMK4msjwOes4nYBg) is what I meant.
Here is the list of sponsors:
10XGenomics
Ecoscope
AWS
Turism Vancouver
ASHG
Genome BC
ACM-W
Affymetrix
Bioinformatics
github
SCWIST
Amazon

**Comment by santina** [comment]
Sounds good! 🖊  🎨

**Comment by adrisua** [comment]
@santina Would you mind doing two signs for each of the following sponsors: Affymetrix, SCWIST and 10XGenomics. Each is having a table. Thanks!

**Comment by daisieh** [comment]
I love making signs if it's not too late to volunteer.

**Comment by daisieh** [comment]
> What do you mean by " one that we could fold in a triangle " ?

I assume she means ones that are tents for tables: you'd just print on the top half of the sheet and then fold it into a tent.

**Comment by ababaian** [comment]
Sounds like a perfect job for a keen volunteer @daisieh , thanks for helping out.

**Comment by santina** [comment]
@daisieh  Do you wanna get together on Thursday or Friday night to do a arts and craft night?  We can go for dinner and spend a fun night making stuff together!  :) 

What we would need to make
(From Adriana) : 
- Signs for each of the 8 teams (triangular tent on the table and flat sheets on the side of the table) that contain the team numbers and the sponsor logos (listed in a previous comment)
- Signs for the sponsors that are tabling

Other things I would really like to do if we have time / enough help: 
- A giant logo of hackseq - I thinking of getting some black foam/paper and cut out some 0s and 1s, which then we can use to assemble into a logo that we can paste on a wall in the hall. 
- Big print-outs (tabloid size) of the daily schedule 
- tabloid printouts of other sponsors to be placed next to the hackseq logo
- Food table sign, registration table sign

**Comment by adrisua** [comment]
That sounds super fun. Just be mindful this is not in our budget so we might not be able to reimburse you. I was planing on printing the stuff at home on Friday. Let me know.

**Comment by daisieh** [comment]
Would you guys want to come to my place to make the stuff either tomorrow or Friday? I have a very nice color printer and an insanely large amount of paper crafting stuff (120 lb white card stock, a paper cutter, exacto knives, cutting mats). Someone would have to get the black foam and any larger printed materials (my printer doesn't print up to tabloid), but other than that I think I'd have everything we need.

**Comment by santina** [comment]
Mmm let's try tomorrow because I'd get a bit stressed out on Friday. 

You sound well stocked, that's awesome! Where do you live? Do you not mind using your color printer? We can also meet at my lab where we can use the color printer in the building.  Since this is a public repo, you can send me private messages on slack so we can figure out the logistics for tomorrow ! :)

**Comment by daisieh** [comment]
Are Amazon and AWS two separate sponsors? Is Bioinformatics the journal BMC Bioinformatics or some other entity?

**Comment by ababaian** [comment]
Amazon is AWS but we also have ACM-W. Bioinformatics is the website bioinformatics.ca

See: http://www.hackseq.com/partners/ and click on links for info :)

**Comment by daisieh** [comment]
![team-tent-preview](https://cloud.githubusercontent.com/assets/1827728/19367556/95e4ff7a-9150-11e6-81a8-41d11308c99d.jpg)

Something like this for the table tents?

**Comment by santina** [comment]
The content is there! I think the number should be centered and bigger and the word "team" is not needed. The opacity can be a little lighter for the logos compared to the number (since that's the main purpose of the team placard). The images look a bit pixelated. Let's get an image asset for all the sponsor logos and talk about how arrange things later :)

**Comment by daisieh** [comment]
This is a preview picture; the actual sign is not pixelated.

**Comment by daisieh** [comment]
I added a pdf version of the printable schedule to the repo (PR #71); I did the layout in Pages so I didn't think that it would be compatible enough with most folks to bother putting up the original. If you have text changes you'd like me to make, comment on the PR and I'll fix them.

**Comment by Brittdrog** [comment]
@santina @daisieh awesome work! Are you guys also making a registration sheet which lists all the participants and their teams (including which people will be absent some of the days) - so that we can keep track of attendance? Or would you like me to work on this?

**Comment by daisieh** [comment]
I don't have access to that information, so I didn't do that. If you could do it, that would be great.

**Comment by Brittdrog** [comment]
OK perfect - will do.

**Comment by santina** [comment]
@Brittdrog I think that can be done electronically for easy look-up and record.

**Comment by Brittdrog** [comment]
@santina - done:-)
