### ISSUE TITLE
Draft email for team leaders

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#65]
- What to do before hackseq (info to communicate to the team)
- AWS info
- responsibilities and support during hackseq

**Comment by Brittdrog** [comment]
The email to the participants and team leaders with the final hackseq details has been sent. Is there anything else that we need to send specifically to the team leaders?

**Comment by santina** [comment]
It's mostly to remind them that they want to remind their team members what to prepare before hackseq (software to download, technologies to learn), our policy on AWS credits and other resources we have. Bruno actually sent an email before (https://github.com/hackseq/October_2016_private/issues/29#issuecomment-246078336) We can reiterate any important information there.

**Comment by Brittdrog** [comment]
@santina - good idea. I have shortened the original email that @brunogrande created to reiterate the important info (see draft [here](https://docs.google.com/document/d/1viTZnO9frQ6nB6iu_dY63-P5FCAxdoITSDNXRoCAbGM/edit?usp=sharing)). If there is anything I have missed, please let me know. I will send out the email tomorrow or Wednesday.

**Comment by adrisua** [comment]
Should we add in that email information about the final presentations? Each team should prepare a 5 - 10 min presentation about their work and plans to submit a manuscript (see [here](https://github.com/hackseq/October_2016_private/issues/27)) after hackseq. We will be giving each team up to $200 to cover publication fees if they submit it before November 15th.

**Comment by adrisua** [comment]
They should upload their final presentations to github before 3:45 pm on Monday. How does that sound?

**Comment by Brittdrog** [comment]
Thanks @adrisua - I have added a section to the email addressing the final presentation and publication. Can you check if you think this looks OK? Are we expecting teams to make slides that they will present or can they present their projects freestyle? I could add a phrase that gives them the option to do either? Is there anything else that I missed?

**Comment by Brittdrog** [comment]
I have made some final adjustments to the [email](https://docs.google.com/document/d/1viTZnO9frQ6nB6iu_dY63-P5FCAxdoITSDNXRoCAbGM/edit), including a heads up that the team leaders will be given a few minutes to introduce themselves and their projects.

I will send the email out tomorrow morning, so let me know if you think of anything else that I may have missed before then.

**Comment by Brittdrog** [comment]
sent
