### ISSUE TITLE
Prepare USB keys for commonly used softwares

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#66]
In the event when internet go down because many people have to download stuff, we should have a USB with the software. 
Examples: 
- RStudio 
- Git

**Comment by BrunoGrandePhD** [comment]
I will start putting something together.

**Comment by BrunoGrandePhD** [comment]
Downloading for Windows, OS X and Linux (where applicable):
- Git
- Anaconda Python distribution (Python 2 and 3)
- R
- Rstudio
- Cygwin
- Git Bash
- Putty

**Comment by santina** [comment]
There will be two USB (looking identical, labelled 'iGSN') at hackseq with those softwares.
