### ISSUE TITLE
Stationary to buy

### ISSUE THREAD

**Issue by Brittdrog** [hackseq/October_2016#67]
I will be buying the stationary for _hackseq_ this weekend as follows:
- Flip boards
- Sharpies
- Red sticky notes
- Scrap paper

Is there anything else that we need to get?

**Comment by Brittdrog** [comment]
I have bought the stationary as follows:
- 8 [flip charts](http://www.staples.ca/en/ICONEX-NCR-Presentation-Pad-with-Easel-Stand-19-1-2-x-27-63950-/product_395546_2-CA_1_20001) ($19.65 each) - I bought one board for each team so that the different teams don't need to share
- 16 sharpies ($21.24)
- Sticky notes ($9.96) - there weren't any red ones only, but seeing as though we don't need red vs. green, I thought this would be OK
- 10 pads of paper ($22.92)

The total comes to $236.68. Is everyone happy with these purchases? 

@ababaian are you still organizing name tags with the hackseq logo on?

**Comment by ababaian** [comment]
Hey all I'm back. Let me know what I have to do =D

Yes @Brittdrog I can make nametags with the hackseq logo on them for participants.

**Comment by adrisua** [comment]
How much would be the name tags @ababaian? During our last meeting we discussed it will be ok to have the regular ones. Just to save costs.

**Comment by ababaian** [comment]
I was going to buy regular ones and print on the logo myself ; )

So not much
