### ISSUE TITLE
Prepare the document for terms and agreement, photo release consent form. 

### ISSUE THREAD

**Issue by santina** [hackseq/October_2016#68]

**Comment by santina** [comment]
Hi @hackseq/steering_committee,  I found some templates for the photo release form, such as [this](http://www.scouts.ca/sites/default/files/PhotographyReleaseForm.pdf). They're relatively straightforward. 

However, the terms and agreement is much more complicated. I think [this one](https://intx15.ncta.com/wp-content/uploads/2015/04/INTXHACK15-HackathonParticipantAgreement.pdf) is a fairly good example, but obviously we would need to modify it to suit our needs.  

Do you think it's worth it that we come up with a terms and agreement form. If so, should we print out 100 copies or have them somehow electronically signed it? 

Thanks!

**Comment by adrisua** [comment]
Since we are giving a price and are making everything open source, I think it would be a good idea.

**Comment by sjackman** [comment]
Here's a link to the UBC Consent to Use of Image form: http://universitycounsel.ubc.ca/files/2011/01/Final-Consent-to-use-of-Image-Nov-23-10.pdf

Dow we need signed terms and agreements, and for what purpose?

**Comment by santina** [comment]
Honestly not sure, @DCGenomics did your hackathon have do this?

**Comment by DCGenomics** [comment]
We ask repeatedly if there are any objections to pictures and ask everyone
else to act as witnesses.

That said, Im not sure if that would be sufficient under canadian law.

Cheers! (so excited about hackseq!)

Ben

**Comment by santina** [comment]
Thanks! We'll prepare a photo consent form then. My computer has a stylus so we can just use that without having to print paper.

@DCGenomics What about something like a participant agreement such as [this](https://intx15.ncta.com/wp-content/uploads/2015/04/INTXHACK15-HackathonParticipantAgreement.pdf) ?

**Comment by sjackman** [comment]
I understand the purpose of the image consent form. What's the purpose of the participant agreement? I'd rather not use any legal documents we don't fully understand and for which we don't have a purpose in mind.

**Comment by BrunoGrandePhD** [comment]
@hackseq/steering_committee: Who is the person who mentioned that we needed a participant agreement? Could they clarify what they meant?

**Comment by minisciencegirl** [comment]
I think I mentioned this (not a participant agreement, but a release of liabilities/ waiver of claims) - I have attached the following two example forms. Let me know if we do want this and I can draft one up. I like @santina suggestion of keeping this on her computer so we don't have to print out 100 forms.

[Doc_-_2016_SOS_retreat_waiver55299.pdf](https://github.com/hackseq/October_2016/files/530015/Doc_-_2016_SOS_retreat_waiver55299.pdf)

[Event_Waiver.pdf](https://github.com/hackseq/October_2016/files/530016/Event_Waiver.pdf)

**Comment by sjackman** [comment]
I'm fine with that if we think it's necessary. (I really can't say whether it is or not. IANAL).
How would the participants sign the form without printing 100 forms?

**Comment by minisciencegirl** [comment]
FYI: @santina's participant form also include a section on release of liabilities/ waiver of claims. So that document is fine as well.
I think photo release form is necessary. Participant forms can be take it or leave it.

**Comment by santina** [comment]
Didn't do. Mami (a volunteer) asked if people are okay with their pictures taken.
