### ISSUE TITLE
Crowdsourcing electric kettles

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/October_2016#69]
Who among the @hackseq/steering_committee can bring an electric kettle for brewing tea? I think we just need 2-3 kettles. 

Santina and I can bring ours.

**Comment by adrisua** [comment]
I can bring another one. Do we need power bars and extension cords as well?

**Comment by santina** [comment]
Mm I guess for hackseq in general, we can bring whatever we think would be helpful. Kettles, extension cords, USB cords, USB keys, extra utensils, paper towel, etc.

**Comment by BrunoGrandePhD** [comment]
I think two kettles is enough. And there are enough power sockets on the long table for both kettles.
