### ISSUE TITLE
Fundraising will be done through SCWIST

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#7]
@hackseq/steering_committee 
Since time is limiting and registering a non-profit society requires a fairly amount of work, we will be receiving the funds through SCWIST. They will assist us with bookkeeping (but won’t be able to provide tax receipts because funds are for a specific cause). 
@ttimbers Would you mind sending a reminder to everyone about the meeting the week before? I started an agenda here: [October_2016/meeting_notes/Agenda_May.md](https://github.com/hackseq/October_2016/blob/master/meeting_notes/Agenda_May.md)
Thanks!

**Comment by sjackman** [comment]
Works for me. Is any further discussion needed, and can this issue be closed?
