### ISSUE TITLE
email tracking

### ISSUE THREAD

**Issue by adrisua** [hackseq/October_2016#8]
@GalenWright Would you like to be in charge of the hackseq gmail account? 
1. Keep track of upcoming emails
2. Answer or direct emails to the corresponding person
3. track google forms, etc. 
   It would be fantastic if you could help us with that :)  
   If yes, we need to let everyone know.  
   Thanks!

**Comment by GalenWright** [comment]
Hey @adrisua, sorry for only replying now - we were away in Whistler for the weekend. Good idea, I'm happy to take on that role
